# German translation for sbackup
# Copyright (c) (c) 2006 Canonical Ltd, and Rosetta Contributors 2006
# This file is distributed under the same license as the sbackup package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: sbackup\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-01-10 22:47+0100\n"
"PO-Revision-Date: 2011-02-06 11:45+0000\n"
"Last-Translator: Jean-Peer Lorenz <Unknown>\n"
"Language-Team: German <de@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-01-11 04:46+0000\n"
"X-Generator: Launchpad (build 16412)\n"

#: src/sbackup/backupproc.py:169 src/sbackup/pkginfo.py:85
#, python-format
msgid "SBackup Daemon <%(login)s@%(hostname)s>"
msgstr "SBackup Daemon <%(login)s@%(hostname)s>"

#: src/sbackup/backupproc.py:173
#, python-format
msgid "[SBackup] [%(profile)s] Report of %(date)s"
msgstr "[SBackup] [%(profile)s] Bericht vom %(date)s"

#: src/sbackup/backupproc.py:178 src/sbackup/core/profile_handler.py:282
msgid "No log file specified."
msgstr "Es wurde keine Protokolldatei angegeben."

#: src/sbackup/backupproc.py:183
msgid "Unable to find log file."
msgstr "Protokolldatei konnte nicht gefunden werden."

#: src/sbackup/backupproc.py:251
msgid ""
"Critical Error: No configuration file for the default profile was found!\n"
"\n"
"Now continue processing remaining profiles."
msgstr ""
"Kritischer Fehler: Es wurde keine Konfiguration für das Standardprofil "
"gefunden!\n"
"\n"
"Es wird mit den verbleibenden Profilen fortgefahren."

#: src/sbackup/backupproc.py:302
msgid "Backup was canceled by user."
msgstr "Die Sicherung wurde vom Benutzer abgebrochen."

#: src/sbackup/backupproc.py:307
msgid "An error occurred during the cancellation of backup:"
msgstr "Während des Abbruchs der Sicherung ist ein Fehler aufgetreten:"

#: src/sbackup/backupproc.py:313
msgid "An error occurred during the backup:"
msgstr "Während der Sicherung trat folgender Fehler auf:"

#: src/sbackup/backupproc.py:330
msgid "Error when sending email:"
msgstr "Fehler beim Versenden der E-Mail:"

#: src/sbackup/backupproc.py:361
msgid "The following error(s) occurred before:"
msgstr "Die folgenden Fehler sind bisher aufgetreten:"

#: src/sbackup/backupproc.py:532
#, python-format
msgid ""
"Backup is not being started.\n"
"%s"
msgstr ""
"Sicherung wird nicht ausgeführt.\n"
"%s"

#: src/sbackup/pkginfo.py:42
msgid ""
"This is a user friendly backup solution for common desktop needs. If you "
"want to help by submitting bugs, by translating or anything else please "
"visit our website."
msgstr ""
"Eine benutzerfreundliche Backup-Lösung für alltägliche Aufgaben im Desktop-"
"Bereich. Falls Du mithelfen möchtest, z.B. durch das Melden von Fehlern, "
"Übersetzen der Anwendung usw. besuche unsere Webseite."

#: src/sbackup/pkginfo.py:45
msgid "Maintainers:"
msgstr "Betreuer:"

#: src/sbackup/pkginfo.py:49
msgid "Former maintainers:"
msgstr "Ehemalige Betreuer:"

#: src/sbackup/pkginfo.py:53
msgid "Contributors:"
msgstr "Mitwirkende:"

#: src/sbackup/pkginfo.py:70
msgid "translator-credits"
msgstr ""
"Übersetzer\n"
"\n"
"Launchpad Contributions:\n"
"  Achim Richter https://launchpad.net/~marabu\n"
"  Andreas Meyer https://launchpad.net/~meyer-greiz\n"
"  Andreas Tarp https://launchpad.net/~andreas-tarp\n"
"  Dirk Salewski https://launchpad.net/~dsalewski-deactivatedaccount\n"
"  Georg Engelmann https://launchpad.net/~georg-engelmann\n"
"  Jacek Zmudzki https://launchpad.net/~jacek-zmudzki\n"
"  Jean-Peer Lorenz https://launchpad.net/~peer.loz\n"
"  Johnny https://launchpad.net/~johnnym1\n"
"  Kai Schroeder https://launchpad.net/~kai-schroeder\n"
"  Martin Schaaf https://launchpad.net/~mascha\n"
"  Martin Schröder https://launchpad.net/~martinschroeder\n"
"  Matthias Rosenkranz https://launchpad.net/~rose\n"
"  Matthäus Brandl https://launchpad.net/~matthaeus\n"
"  Steffen Banhardt https://launchpad.net/~steffenbanhardt\n"
"  toomuch https://launchpad.net/~toomuch"

#: src/sbackup/ar_backend/tar.py:109 src/sbackup/ar_backend/tar.py:167
#: src/sbackup/ar_backend/tar.py:213
msgid "Invalid archive type."
msgstr "Ungültiger Archivtyp."

#: src/sbackup/ar_backend/tar.py:123
#, python-format
msgid "Effective path for `%s` is not available"
msgstr "Effektiver Pfad für `%s` ist nicht verfügbar"

#: src/sbackup/ar_backend/tar.py:295
#, python-format
msgid "Unable to get effective path for `%s`"
msgstr "Kann keinen gültigen Pfad für `%s` finden"

#: src/sbackup/ar_backend/tar.py:344
msgid ""
"For the moment split functionality is not compatible with compress option."
msgstr ""
"Zur Zeit ist das Aufteilen von Sicherungen nicht kompatibel zur "
"Komprimierungsfunktion."

#: src/sbackup/ar_backend/tar.py:353 src/sbackup/ar_backend/tar.py:414
#: src/sbackup/core/profile_handler.py:292
#, python-format
msgid "Unable to change permissions for file '%s'."
msgstr "Zugriffsrechte für Datei '%s' konnten nicht geändert werden."

#: src/sbackup/ar_backend/tar.py:362
#, python-format
msgid "Unable to remove temporary file `%(file)s`: %(error)s"
msgstr "Temporäre Datei `%(file)s` konnte nicht entfernt werden: %(error)s"

#: src/sbackup/ar_backend/tar.py:378
msgid "Launching TAR to make incremental backup."
msgstr "Ausführen von TAR um eine inkrementelle Sicherung zu erstellen."

#: src/sbackup/ar_backend/tar.py:407
msgid "Unable to find the SNAR file to make an incremental backup."
msgstr ""
"Die SNAR-Datei zur Erstellung einer inkrementellen Sicherung wurde nicht "
"gefunden."

#: src/sbackup/ar_backend/tar.py:408
msgid "Falling back to full backup."
msgstr ""
"Es wird auf die Erstellung einer vollständigen Sicherung ausgewichen."

#: src/sbackup/ar_backend/tar.py:450
msgid "Launching TAR to make a full backup."
msgstr "Ausführen von TAR um eine vollständige Sicherung zu erstellen."

#: src/sbackup/ar_backend/tar.py:517
msgid "Leading '/' from member names were removed."
msgstr "Führende '/' wurden von den Pfaden im Archiv entfernt."

#: src/sbackup/ar_backend/tar.py:519
msgid "Leading '/' from hard link targets were removed."
msgstr ""
"Führende '/' wurden von den Zielen harter Verknüpfungen im Archiv entfernt."

#: src/sbackup/ar_backend/tar.py:528
#, python-format
msgid "TAR returned a message: %s"
msgstr "TAR gab folgende Mitteilung zurück: %s"

#: src/sbackup/ar_backend/tar.py:530
#, python-format
msgid ""
"TAR returned messages:\n"
"%s"
msgstr ""
"TAR gab folgende Mitteilungen zurück:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:533
msgid "TAR has been finished successfully."
msgstr "TAR wurde erfolgreich beendet."

#: src/sbackup/ar_backend/tar.py:537
#, python-format
msgid "TAR returned a warning: %s"
msgstr "TAR lieferte eine Warnung: %s"

#: src/sbackup/ar_backend/tar.py:539
#, python-format
msgid ""
"TAR returned warnings:\n"
"%s"
msgstr ""
"TAR lieferte Warnungen:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:542
msgid "TAR returned warnings but has been finished successfully."
msgstr "TAR gab Warnungen zurück, konnte aber erfolgreich beendet werden."

#: src/sbackup/ar_backend/tar.py:546
msgid "Unable to finish successfully. TAR terminated with errors."
msgstr ""
"Sicherung war nicht erfolgreich. TAR  wurde aufgrund von Fehlern vorzeitig "
"beendet."

#: src/sbackup/ar_backend/tar.py:727
#, python-format
msgid "Unable to terminate backend process: %s"
msgstr "Der Hintergrund-Prozess konnte nicht beendet werden: %s"

#: src/sbackup/ar_backend/tar.py:760
msgid "Included"
msgstr "Aufgenommen"

#: src/sbackup/ar_backend/tar.py:760
msgid "Not changed"
msgstr "Nicht geändert"

#: src/sbackup/ar_backend/tar.py:760
msgid "Directory"
msgstr "Verzeichnis"

#: src/sbackup/ar_backend/tar.py:788
msgid "Line must be a string"
msgstr "Zeile muss eine Zeichenkette sein"

#: src/sbackup/ar_backend/tar.py:804
msgid "Dumpdir inconsistancy : 'filename' is empty"
msgstr "Verzeichnis zum Ablegen ist inkonsistent: 'filename' ist leer"

#: src/sbackup/ar_backend/tar.py:817
msgid "Dumpdir inconsistancy : 'control' is empty"
msgstr "Verzeichnis zum Ablegen ist inkonsistent: 'control' ist leer"

#: src/sbackup/ar_backend/tar.py:890
#, python-format
msgid "File '%s' does not exist."
msgstr "Die Datei '%s' existiert nicht."

#: src/sbackup/ar_backend/tar.py:1020 src/sbackup/ar_backend/tar.py:1054
#: src/sbackup/ar_backend/tar.py:1154
msgid "The snarfile header is incomplete."
msgstr "Kopf der SNAR-Datei ist unvollständig."

#: src/sbackup/ar_backend/tar.py:1323
msgid "A SnapshotFile is required"
msgstr "Eine Sicherungsdatei wird benötigt"

#: src/sbackup/ar_backend/tar.py:1423
#, python-format
msgid "Directory does not exist: %s."
msgstr "Das Verzeichnis existiert nicht: %s."

#: src/sbackup/core/ConfigManager.py:330
#, python-format
msgid "Profile settings are being read from file '%s'."
msgstr "Einstellungen des Profils werden gelesen aus Datei '%s'."

#: src/sbackup/core/ConfigManager.py:333
#, python-format
msgid ""
"Profile settings are being set to default values. Configuration file is set "
"to '%s'."
msgstr ""
"Einstellungen des Profils werden auf die Standardwerte gesetzt. "
"Konfigurationsdatei wird auf Datei '%s' festgelegt."

#: src/sbackup/core/ConfigManager.py:479
msgid "Option 'target' is missing, aborting."
msgstr "Angabe der Option 'target' fehlt, Abbruch"

#: src/sbackup/core/ConfigManager.py:547
#, python-format
msgid ""
"Error while processing configuration:\n"
"\n"
"%(error)s in line `%(line)s`.\n"
"\n"
"Please check your configuration file."
msgstr ""
"Fehler beim Verarbeiten der Konfiguration:\n"
"\n"
"%(error)s in Zeile `%(line)s`.\n"
"\n"
"Bitte die Konfigurationsdatei überprüfen."

#: src/sbackup/core/ConfigManager.py:588 src/sbackup/core/ConfigManager.py:622
#, python-format
msgid ""
"Unable to evaluate '%(parameter)s' as a dictionary (value got = '%(value)r')."
msgstr ""
"Parameter '%(parameter)s' konnte nicht als assoziatives Feld (Dictionary) "
"ausgewertet werden (übergebener Wert = '%(value)r')."

#: src/sbackup/core/ConfigManager.py:614
#, python-format
msgid ""
"Couldn't evaluate '%(parameter)s' as a dictionary (value got = '%(value)r' )"
msgstr ""
"Parameter '%(parameter)s' konnte nicht als assoziatives Feld (Dictionary) "
"ausgewertet werden (value got = '%(value)r' )"

#: src/sbackup/core/ConfigManager.py:638
msgid "You must provide a dictionary."
msgstr "Ein assoziatives Feld (Dictionary) muss übergeben werden."

#: src/sbackup/core/ConfigManager.py:755
#, python-format
msgid "Log output for [%(profile)s] is directed to file '%(file)s'."
msgstr "Logausgabe für [%(profile)s] wird in Datei '%(file)s' umgeleitet."

#: src/sbackup/core/ConfigManager.py:762
#, python-format
msgid "Log output for [%s] is not directed into a file."
msgstr "Logausgabe für [%s] wird nicht in eine Datei umgeleitet."

#: src/sbackup/core/ConfigManager.py:781
#, python-format
msgid "Unable to rename log file '%(src)s'->'%(dst)s': %(err)s"
msgstr ""
"Protokolldatei konnte nicht umbenannt werden '%(src)s'->'%(dst)s': %(err)s"

#: src/sbackup/core/ConfigManager.py:801
#, python-format
msgid "The config file '%s' couldn't be read!"
msgstr "Konfigurationsdatei '%s' konnte nicht eingelesen werden!"

#: src/sbackup/core/ConfigManager.py:813
#, python-format
msgid "section [%(section)s] in '%(configfile)s' should not exist, aborting"
msgstr ""
"Abschnitt [%(section)s] in '%(configfile)s' sollte nicht existieren, Abbruch"

#: src/sbackup/core/ConfigManager.py:895
msgid "No schedule defined in configuration file. Probing from filesystem."
msgstr ""
"Kein Zeitplan in der Konfiguration definiert. Untersuchung des Dateisystems."

#: src/sbackup/core/ConfigManager.py:988
#: src/sbackup/core/ConfigManager.py:1000
msgid "The config file is not set yet into this ConfigManager"
msgstr ""
"Die Konfigurationsdatei wurde in diesem ConfigManager noch nicht gesetzt"

#: src/sbackup/core/ConfigManager.py:1163
msgid "No receiver set."
msgstr "Kein Empfänger gesetzt."

#: src/sbackup/core/ConfigManager.py:1165
msgid "No SMTP server set."
msgstr "Kein SMTP-Server gesetzt."

#: src/sbackup/core/ConfigManager.py:1168
msgid "Username set but no password specified."
msgstr "Benutzername gesetzt, jedoch kein Passwort festgelegt."

#: src/sbackup/core/ConfigManager.py:1171
msgid "Password set but no username specified."
msgstr "Passwort gesetzt, jedoch kein Benutzername festgelegt."

#: src/sbackup/core/ConfigManager.py:1174
msgid ""
"A certificate and key file is given while SSL option (smtptls=1) is not "
"set.\n"
"Select SSL in order to use Certificate and Key."
msgstr ""
"Es wurde eine Zertifikatsdatei und eine Schlüsseldatei festgelegt, obwohl "
"die Option SSL (smtptls=1) nicht gesetzt ist.\n"
"Aktivieren Sie SSL, um ein Zertifikat und einen Schlüssel zu verwenden."

#: src/sbackup/core/ConfigManager.py:1178
msgid ""
"When specifying a SSL certificate or key file, a key file resp. certificate "
"is mandatory."
msgstr ""
"Wenn ein SSL Zertifikat oder eine Schlüsseldatei festgelegt wurde, ist die "
"Angabe einer Schlüsseldatei bzw. eines Zertifikats notwendig."

#: src/sbackup/core/ConfigManager.py:1373
msgid "Default Profile"
msgstr "Standardprofil"

#: src/sbackup/core/ConfigManager.py:1374
msgid "Unknown Profile"
msgstr "Unbekanntes Profil"

#: src/sbackup/core/ConfigManager.py:1428
msgid "Unlimited"
msgstr "Unbegrenzt"

#: src/sbackup/core/ConfigManager.py:1429
msgid "100 MiB"
msgstr "100 MiB"

#: src/sbackup/core/ConfigManager.py:1430
msgid "250 MiB"
msgstr "250 MiB"

#: src/sbackup/core/ConfigManager.py:1431
msgid "650 MiB"
msgstr "650 MiB"

#: src/sbackup/core/ConfigManager.py:1432
msgid "2 GiB (FAT16)"
msgstr "2 GiB (FAT16)"

#: src/sbackup/core/ConfigManager.py:1433
msgid "4 GiB (FAT32)"
msgstr "4 GiB (FAT32)"

#: src/sbackup/core/ConfigManager.py:1434 src/sbackup/ui/configgui.py:279
#: src/sbackup/ui/configgui.py:1418
msgid "Custom"
msgstr "Benutzerdefiniert"

#: src/sbackup/core/ConfigManager.py:1436
msgid "MP3 Music"
msgstr "MP3-Musik"

#: src/sbackup/core/ConfigManager.py:1437
msgid "AVI Video"
msgstr "AVI-Videos"

#: src/sbackup/core/ConfigManager.py:1438
#: src/sbackup/core/ConfigManager.py:1439
msgid "MPEG Video"
msgstr "MPEG-Videos"

#: src/sbackup/core/ConfigManager.py:1440
msgid "Matrjoshka Video"
msgstr "Matroska-Videos"

#: src/sbackup/core/ConfigManager.py:1441
msgid "OGG Multimedia container"
msgstr "OGG-Multimedia-Container"

#: src/sbackup/core/ConfigManager.py:1442
msgid "CD Images"
msgstr "CD-Abbilder"

#: src/sbackup/core/RestoreManager.py:80
#, python-format
msgid "File '%s' not found in the backup snapshot files list"
msgstr "Datei '%s' konnte in der Sicherungsdatei nicht gefunden werden."

#: src/sbackup/core/RestoreManager.py:82
#, python-format
msgid ""
"File '%(filename)s' not found in snapshot's [%(snapshotname)s] files list, "
"Skipped."
msgstr ""
"Datei '%(filename)s' wurde nicht in der Dateiliste der Sicherung "
"[%(snapshotname)s] gefunden. Wird übersprungen."

#: src/sbackup/core/SnapshotManager.py:114
#, python-format
msgid "Snapshot '%s' not found "
msgstr "Sicherung '%s' wurde nicht gefunden "

#: src/sbackup/core/SnapshotManager.py:210
#, python-format
msgid "Invalid snapshot `%(name)s` found: Name of snapshot not valid."
msgstr ""
"Ungültige Sicherung `%(name)s` gefunden: Name der Sicherung ist nicht gültig."

#: src/sbackup/core/SnapshotManager.py:213
#, python-format
msgid "Invalid snapshot `%(name)s` found: %(error_cause)s."
msgstr "Ungültige Sicherung `%(name)s` gefunden: %(error_cause)s."

#: src/sbackup/core/SnapshotManager.py:286
msgid "The snarfile header is incomplete !"
msgstr "Dateikopf der 'snar'-Datei ist unvollständig!"

#: src/sbackup/core/SnapshotManager.py:429
#, python-format
msgid ""
"Snapshot '%s' is already Full, nothing to do (not changing it to full)."
msgstr ""
"Sicherung '%s' ist bereits eine vollständige Sicherung, es gibt nichts zu "
"tun (wird nicht in eine volle Sicherung umgewandelt)."

#: src/sbackup/core/profile_handler.py:101
#, python-format
msgid "Running of hooks: %s"
msgstr ""

#: src/sbackup/core/profile_handler.py:111
msgid "Preparation of backup process"
msgstr "Vorbereitung des Sicherungsvorgangs"

#: src/sbackup/core/profile_handler.py:146
#, python-format
msgid "Snapshot '%(name)s' is being made."
msgstr "Sicherung '%(name)s' wird erstellt."

#: src/sbackup/core/profile_handler.py:154
#, python-format
msgid "Setting Base to '%(value)s'."
msgstr "Festlegen der Ausgangssicherung auf '%(value)s'."

#: src/sbackup/core/profile_handler.py:163
msgid "Setting packages File."
msgstr "Erstellen der Paket-Liste."

#: src/sbackup/core/profile_handler.py:169
msgid "Problem when setting the packages list: "
msgstr "Problem beim Festlegen der Paketliste: "

#: src/sbackup/core/profile_handler.py:173
msgid "Setting Excludes File."
msgstr "Schreiben der 'Nicht Sichern'-Liste."

#: src/sbackup/core/profile_handler.py:181
#, python-format
msgid "Setting compression format to `%s`"
msgstr "Komprimierung festgelegt auf `%s`"

#: src/sbackup/core/profile_handler.py:188
#, python-format
msgid "Setting size of archive chunks to %s"
msgstr "Größe der Teilarchive festgelegt auf %s"

#: src/sbackup/core/profile_handler.py:195
msgid "Option 'Follow symbolic links' is enabled."
msgstr "Option 'Symbolischen Links folgen' ist aktiviert."

#: src/sbackup/core/profile_handler.py:197
msgid "Option 'Follow symbolic links' is disabled."
msgstr "Option 'Symbolischen Links folgen' ist nicht aktiviert."

#: src/sbackup/core/profile_handler.py:206
msgid "Snapshot is being committed"
msgstr "Sicherung wird geschrieben"

#: src/sbackup/core/profile_handler.py:220
#, python-format
msgid "Error while purging old snapshots: %s"
msgstr "Fehler während des Entfernens alter Sicherungen: %s"

#: src/sbackup/core/profile_handler.py:222
msgid "Backup process finished."
msgstr "Sicherungsvorgang wurde beendet."

#: src/sbackup/core/profile_handler.py:229
msgid "Inspect file system and collect file infos"
msgstr "Untersuchen des Dateisystems und sammeln der Dateiinformationen"

#: src/sbackup/core/profile_handler.py:240
msgid "Summary of backup"
msgstr "Zusammenfassung der Sicherung"

#: src/sbackup/core/profile_handler.py:241
#, python-format
msgid "Number of directories: %s."
msgstr "Anzahl von Verzeichnissen: %s."

#: src/sbackup/core/profile_handler.py:242
#, python-format
msgid "Total number of files: %s."
msgstr "Gesamtanzahl von Dateien: %s."

#: src/sbackup/core/profile_handler.py:243
#, python-format
msgid "Number of symlinks: %s."
msgstr "Anzahl symbolischer Verknüpfungen: %s."

#: src/sbackup/core/profile_handler.py:244
#, python-format
msgid "Number of files included in snapshot: %s."
msgstr "Anzahl der in diesen Schnappschuss eingeschlossenen Dateien: %s."

#: src/sbackup/core/profile_handler.py:245
#, python-format
msgid "Number of new files (also included): %s."
msgstr "Anzahl neuer Dateien (ebenfalls eingeschlossen): %s."

#: src/sbackup/core/profile_handler.py:246
#, python-format
msgid "Number of files skipped in incremental snapshot: %s."
msgstr ""
"Anzahl übersprungener Dateien in diesem inkrementellen Schnappschuss: %s."

#: src/sbackup/core/profile_handler.py:247
#, python-format
msgid "Number of items forced to be excluded: %s."
msgstr "Anzahl von Elementen, die ausgeschlossen werden mussten: %s."

#: src/sbackup/core/profile_handler.py:248
#, python-format
msgid "Number of items to be excluded by config: %s."
msgstr ""
"Anzahl von Elementen, die auf Grund von Benutzereinstellungen ausgeschlossen "
"wurden: %s."

#: src/sbackup/core/profile_handler.py:249
#, python-format
msgid "Maximum free size required is '%s'."
msgstr "Maximal benötigter freier Speicherplatz ist '%s'."

#: src/sbackup/core/profile_handler.py:255
#, python-format
msgid "Available disk size is '%s'."
msgstr "Verfügbarer Speicherplatz ist '%s'."

#: src/sbackup/core/profile_handler.py:257
#, python-format
msgid ""
"Not enough free space in the target directory for the planned backup (free: "
"%(freespace)s, required: %(neededspace)s)."
msgstr ""
"Für die geplante Sicherung ist nicht genügend freier Speicher im "
"Zielverzeichnis verfügbar (frei: %(freespace)s, benötigt: %(neededspace)s)."

#: src/sbackup/core/profile_handler.py:277
msgid "Unable to copy log. File access is not initialized."
msgstr ""
"Protokolldatei konnte nicht kopiert werden. Dateizugriff wurde nicht "
"initialisiert."

#: src/sbackup/core/profile_handler.py:295
#, python-format
msgid "Unable to copy log file: %s"
msgstr "Protokolldatei konnte nicht kopiert werden: %s"

#: src/sbackup/core/profile_handler.py:297
msgid "Unable to find logfile to copy into snapshot."
msgstr "Logdatei wurde nicht gefunden."

#: src/sbackup/core/profile_handler.py:299
msgid "No snapshot to copy logfile."
msgstr "Keine Sicherung vorhanden um das Log zu kopieren."

#: src/sbackup/core/profile_handler.py:306
msgid "Processing of profile was canceled on user request\n"
msgstr ""
"Die Bearbeitung des Sicherungsprofils wurde auf Wunsch des Benutzers "
"abgebrochen\n"

#: src/sbackup/core/profile_handler.py:323
msgid "Processing of profile successfully finished (no errors)\n"
msgstr ""
"Die Bearbeitung des Sicherungsprofils wurde erfolgreich beendet (keine "
"Fehler)\n"

#: src/sbackup/core/profile_handler.py:329
#, python-format
msgid "Processing of profile failed with error: %s\n"
msgstr ""
"Die Bearbeitung des Sicherungsprofils ist fehlgeschlagen. Fehler: %s\n"

#: src/sbackup/core/profile_handler.py:340
#, python-format
msgid "Backup destination: %s"
msgstr "Sicherungsziel: %s"

#: src/sbackup/core/profile_handler.py:344
msgid "Unable to find destination directory."
msgstr "Zielverzeichnis konnte nicht gefunden werden."

#: src/sbackup/core/profile_handler.py:363
msgid "Unable to find destination directory even after retry."
msgstr ""
"Zielverzeichnis konnte auch nach einem weiteren Versuch nicht gefunden "
"werden."

#: src/sbackup/core/profile_handler.py:364
#: src/sbackup/core/profile_handler.py:371
#, python-format
msgid "Target directory '%(target)s' does not exist."
msgstr "Zielverzeichnis '%(target)s' existiert nicht."

#: src/sbackup/core/profile_handler.py:377
#, python-format
msgid "Unable to access destination: %s"
msgstr "Auf das Zielverzeichnis konnte nicht zugegriffen werden: %s"

#: src/sbackup/core/snapshot.py:134
msgid "Snapshot is inconsistent: __name is not set "
msgstr "Schnappschuss ist inkonsistent: __name ist nicht festgelegt "

#: src/sbackup/core/snapshot.py:145
#, python-format
msgid "Name of snapshot '%s' doesn't match requirement"
msgstr "Name der Sicherung '%s' erfüllt Anforderung nicht"

#: src/sbackup/core/snapshot.py:239
msgid "Snapshot is inconsistent: __snapshotpath is not set "
msgstr "Schnappschuss ist inkonsistent: __snapshotpath ist nicht festgelegt "

#: src/sbackup/core/snapshot.py:318
#, python-format
msgid ""
"The snapshot compression format is supposed to be '%s' but the corresponding "
"well named file wasn't found"
msgstr ""
"Das Format der Sicherung sollte '%s' sein, jedoch wurde ein entsprechend "
"benannte Datei nicht gefunden"

#: src/sbackup/core/snapshot.py:342
#, python-format
msgid ""
"%(file)s doesn't contain valid value. Ignoring incomplete or non - backup "
"directory. "
msgstr ""
"%(file)s enthält keinen gültigen Wert. Unvollständiges oder unbekanntes "
"Verzeichnis wird ignoriert. "

#: src/sbackup/core/snapshot.py:478
#, python-format
msgid "Name of Snapshot not valid : %s"
msgstr "Name der Sicherung ist ungültig: %s"

#: src/sbackup/core/snapshot.py:496
#, python-format
msgid "Name of base not valid : %s"
msgstr "Name der Ausgangssicherung ist ungültig: %s"

#: src/sbackup/core/snapshot.py:542
#, python-format
msgid "Invalid name of snapshot: %s"
msgstr "Ungültiger Name der Sicherung: %s"

#: src/sbackup/core/snapshot.py:546
msgid "Unable to read mandatory file `ver`"
msgstr "Die notwendige Datei `ver` konnte nicht gelesen werden"

#: src/sbackup/core/snapshot.py:591
msgid "Base name must be set for incremental backup."
msgstr ""
"Für eine inkrementelle Sicherung muss der Name einer Ausgangssicherung "
"festgelegt sein."

#: src/sbackup/fs_backend/_fuse_fam.py:106
msgid "Initializing FUSE File Access Manager."
msgstr "Initialisierung des FUSE File Access Manager."

#: src/sbackup/fs_backend/_fuse_fam.py:129
msgid "Terminating FUSE File Access Manager."
msgstr "Beendigung des FUSE File Access Manager."

#: src/sbackup/fs_backend/_fuse_utils.py:45
#: src/sbackup/fs_backend/_gio_utils.py:109
msgid "SFTP"
msgstr "SFTP"

#: src/sbackup/fs_backend/_fuse_utils.py:46
#: src/sbackup/fs_backend/_gio_utils.py:110
msgid "SSH"
msgstr "SSH"

#: src/sbackup/fs_backend/_fuse_utils.py:47
#: src/sbackup/fs_backend/_gio_utils.py:111
msgid "FTP"
msgstr "FTP"

#: src/sbackup/fs_backend/_gio_fam.py:100
msgid "Initializing GIO File Access Manager."
msgstr "Initialisierung des GIO Dateizugriffs."

#: src/sbackup/fs_backend/_gio_fam.py:114
msgid "Terminating GIO File Access Manager."
msgstr "Beendigung des GIO Dateizugriffs."

#: src/sbackup/fs_backend/_gio_utils.py:95
msgid "Unknown error code:"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:112
msgid "NFS"
msgstr "NFS"

#: src/sbackup/fs_backend/_gio_utils.py:113
msgid "SMB"
msgstr "SMB"

#: src/sbackup/fs_backend/_gio_utils.py:193
msgid "Unable to get mount: path is not mounted"
msgstr "Mountpunkt konnte nicht ermittelt werden: Pfad ist nicht eingebunden"

#: src/sbackup/fs_backend/_gio_utils.py:195
msgid "Unable to get mount: path not found when mounting (is probably local)"
msgstr ""
"Mountpunkt konnte nicht ermittelt werden: Einzubindener Pfad wurde nicht "
"gefunden (ist wahrscheinlich lokal)"

#: src/sbackup/fs_backend/_gio_utils.py:197
#: src/sbackup/fs_backend/_gio_utils.py:200
#, python-format
msgid "Unable to get mount: %s"
msgstr "Mountpunkt konnte nicht ermittelt werden: %s"

#: src/sbackup/fs_backend/_gio_utils.py:250
msgid "Unable to un-set mount flag: path is not stored"
msgstr ""
"Mountflag konnte nicht zurück gesetzt werden: Pfad wurde nicht gesichert"

#: src/sbackup/fs_backend/_gio_utils.py:352
msgid "Path is already mounted."
msgstr "Pfad ist bereits eingebunden."

#: src/sbackup/fs_backend/_gio_utils.py:380
msgid "Path is not mounted."
msgstr "Pfad ist nicht eingebunden."

#: src/sbackup/fs_backend/_gio_utils.py:887
msgid "test specified path for existence using GIO"
msgstr "Testen des festgelegten Pfades auf Existenz mittels GIO"

#: src/sbackup/fs_backend/_gio_utils.py:900
msgid "Create testdir"
msgstr "Erstelle Testverzeichnis"

#: src/sbackup/fs_backend/_gio_utils.py:905
msgid "Test testfile for existence"
msgstr "Testdatei auf Existenz prüfen"

#: src/sbackup/fs_backend/_gio_utils.py:912
msgid "Create file"
msgstr "Datei erstellen"

#: src/sbackup/fs_backend/_gio_utils.py:919
msgid "Re-read test file"
msgstr "Testdatei erneut einlesen"

#: src/sbackup/fs_backend/_gio_utils.py:931
msgid "Remove file"
msgstr "Datei entfernen"

#: src/sbackup/fs_backend/_gio_utils.py:933
msgid "Remove dir"
msgstr "Verzeichnis entfernen"

#: src/sbackup/fuse_plugins/__init__.py:160
#, python-format
msgid "Unable to import plugin `%(plugin_name)s`: %(error_cause)s "
msgstr ""
"Plugin `%(plugin_name)s` konnte nicht importiert werden: %(error_cause)s "

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:117
#, python-format
msgid ""
"Couldn't found external application 'curlftpfs' needed for handling of ftp "
"sites: %s"
msgstr ""
"Konnte externe Anwendung 'curlftpfs' nicht finden. Diese wird zur Handhabung "
"von FTP Sites benötigt: %s"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:127
#: src/sbackup/fuse_plugins/sftpFuseFAM.py:124
#, python-format
msgid "Couldn't mount '%(server)s' into '%(mountpoint)s' : %(error)s"
msgstr ""
"'%(server)s' konnte nicht in '%(mountpoint)s' eingebunden werden: %(error)s"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:141
msgid "FTP schema is: ftp://user:pass@server/anything"
msgstr ""
"Schema für FTP ist: "
"ftp://benutzername:passwort@servername.com/ein_beliebiger_pfad"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:188
#, python-format
msgid ""
"Error matching the schema 'ftp://user:pass@server/anything' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Beim Auflösen des FTP-Adressformates 'ftp://user:pass@server/anything' ist "
"ein Fehler aufgetreten: '%s' (auf den Servernamen muss zwingend '/' folgen)"

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:114
#, python-format
msgid ""
"Couldn't found external application 'curlftpfs' needed for handling of sftp "
"sites: %s"
msgstr ""
"Für die Verwendung von SFTP-Zielen wird das externe Programm 'curlftpfs' "
"benötigt. Das Programm 'curlftpfs' wurde nicht gefunden: %s"

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:138
msgid "SFTP schema is like : sftp://user:pass@server/anything"
msgstr ""
"Das Format für SFTP-Adressen lautet: sftp://user:pass@server/anything"

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:185
#, python-format
msgid ""
"Error matching the schema 'sftp://user:pass@server/anything' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Beim Auflösen des SFTP-Adressformates 'sftp://user:pass@server/anything' ist "
"ein Fehler aufgetreten: '%s' (auf den Servernamen muss zwingend '/' folgen)"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:81
#, python-format
msgid ""
"Error matching the schema 'ssh://user:pass@example.com/home/' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Beim Auflösen des SSH-Adressformates 'ssh://user:pass@example.com/home/' ist "
"ein Fehler aufgetreten: '%s' (auf den Servernamen muss zwingend '/' folgen)"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:137
#, python-format
msgid ""
"The sshfs command '%(command)s' didn't perform normally. Output => "
"%(erroroutput)s "
msgstr ""
"Das sshfs-Kommando '%(command)s' wurde nicht korrekt ausgeführt. Ausgabe => "
"%(erroroutput)s "

#: src/sbackup/fuse_plugins/sshFuseFAM.py:142
msgid "SSH schema is like : ssh://user:pass@example.com:33/home/user/backup/"
msgstr ""
"Schema für SSH ist: "
"ssh://benutzername:passwort@servername.com:portnummer/ein_beliebiger_pfad"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:158
#, python-format
msgid ""
"Error matching the schema 'ssh://user:pass@example.com:21/home/' with '%s' "
"(The '/' after server is mandatory)"
msgstr ""
"Fehler beim Prüfen des Schema "
"'ssh://benutzername:passwort@servername.com:portnummer/ein_beliebiger_pfad' "
"mit '%s' (Der Schrägstrich '/' nach der Serverangabe ist notwendig)."

#: src/sbackup/ui/GladeWindow.py:210
msgid ""
"Please make sure the missing directory exists (e.g. by mounting an external "
"disk) or change the specified target."
msgstr ""
"Bitte stellen sie sicher, dass das fehlende Verzeichnis existiert (z.B. "
"durch Einhängen einer externen Festplatte) oder ändern sie den Wert für das "
"Zielverzeichnis entsprechend."

#: src/sbackup/ui/GladeWindow.py:211
#, python-format
msgid ""
"While accessing the backup destination following error occurred:\n"
"\n"
"%s."
msgstr ""
"Während des Zugriffs auf das Backup Zielverzeichnis ist folgender Fehler "
"aufgetreten:\n"
"\n"
"%s."

#: src/sbackup/ui/GladeWindow.py:212 src/sbackup/ui/restoregui.py:797
msgid "Simple Backup error"
msgstr "Simple Backup Fehler"

#: src/sbackup/ui/GladeWindow.py:213
msgid "Unable to access backup destination"
msgstr "Auf das Sicherungsziel konnte nicht zugegriffen werden"

#: src/sbackup/ui/configgui.py:125
msgid "Scheduled backups are available for Administrator users only."
msgstr "Sicherungen nach Zeitplan sind nur für Administratoren möglichen."

#: src/sbackup/ui/configgui.py:135 src/sbackup/ui/configgui.py:144
msgid "Name"
msgstr "Name"

#: src/sbackup/ui/configgui.py:152
msgid "File Type"
msgstr "Dateityp"

#: src/sbackup/ui/configgui.py:187
msgid "Enable"
msgstr "Profil verwenden"

#: src/sbackup/ui/configgui.py:188
msgid "Profile Name"
msgstr "Name des Profils"

#: src/sbackup/ui/configgui.py:285
#, python-format
msgid ""
"Invalid or empty regular expression ('%s') found in configuration. Removed."
msgstr ""
"Ungültigen oder leeren Regulären Ausdruck ('%s') in der Konfiguration "
"gefunden. Wurde entfernt."

#: src/sbackup/ui/configgui.py:292
#, python-format
msgid ""
"Invalid or empty regular expressions found\n"
"in configuration file:\n"
"'%s'\n"
"\n"
"These expressions are not used and were\n"
"removed from the configuration."
msgstr ""
"Ungültige oder leere Reguläre Ausdrücke in\n"
"der Konfiguration gefunden:\n"
"'%s'\n"
"\n"
"Diese Ausdrücke werden nicht benutzt und wurden\n"
"aus der Konfiguration entfernt."

#: src/sbackup/ui/configgui.py:548
msgid ""
"Please make sure the missing directory exists (e.g. by mounting an external "
"disk) or change the specified target to an existing one."
msgstr ""
"Bitte stellen Sie sicher, dass das fehlende Verzeichnis existiert (z. B. "
"indem sie eine externe Festplatte einbinden) oder ändern sie das festgelegte "
"Zielverzeichnis auf ein existierendes Verzeichnis."

#: src/sbackup/ui/configgui.py:549
#, python-format
msgid ""
"Backup target `%s` does not exist.\n"
"\n"
"Attention: The target will be set to the default value. Check this on the "
"destination settings page before saving the configuration."
msgstr ""
"Ziel der Sicherung `%s` existiert nicht.\n"
"\n"
"Achtung: Das Sicherungsziel wird auf den Standardwert zurück gesetzt. Prüfen "
"sie dies bitte im Reiter 'Zielverzeichnis' bevor sie die Änderungen "
"speichern."

#: src/sbackup/ui/configgui.py:551
msgid "Unable to open backup target"
msgstr "Zielverzeichnis der Sicherung konnte nicht geöffnet werden"

#: src/sbackup/ui/configgui.py:623
#, python-format
msgid ""
"%s\n"
"\n"
"A backup profile using default values was created. Save the new "
"configuration in order to use it or check your existing configuration file "
"manually.\n"
"\n"
"Important note: Saving will overwrite your existing invalid configuration."
msgstr ""
"%s\n"
"\n"
"Es wurde ein Sicherungsprofil, welches die Standardwerte verwendet, erzeugt. "
"Bitte die neuen Einstellungen speichern um sie zu verwenden oder die "
"existierende Konfigurationsdatei manuell überprüfen.\n"
"\n"
"Wichtiger Hinweis: Speichern des Profils überschreibt die existierenden "
"ungültigen Einstellungen."

#: src/sbackup/ui/configgui.py:641
#, python-format
msgid "Current profile: %s"
msgstr "Aktuelles Profil: %s"

#: src/sbackup/ui/configgui.py:732
msgid "Already included item !"
msgstr "Eintrag ist bereits enthalten!"

#: src/sbackup/ui/configgui.py:747
msgid "Already excluded item !"
msgstr "Eintrag ist bereits ausgeschlossen!"

#: src/sbackup/ui/configgui.py:759 src/sbackup/ui/configgui.py:1458
msgid "Empty expression. Please enter a valid regular expression."
msgstr ""
"Leeres Suchmuster. Bitte geben Sie einen gültigen regulären Ausdruck als "
"Suchmuster an."

#: src/sbackup/ui/configgui.py:774 src/sbackup/ui/configgui.py:1472
msgid "Provided regular expression is not valid."
msgstr "Der angegebene reguläre Ausdruck ist nicht gültig."

#: src/sbackup/ui/configgui.py:782
msgid "Empty filename or path. Please enter a valid filename or path."
msgstr ""
"Leerer Dateiname oder Pfad. Bitte geben Sie einen gültigen Dateinamen oder "
"Pfad an."

#: src/sbackup/ui/configgui.py:791
msgid ""
"It seems the path you entered does not exists. Do you want to add this "
"incorrect path?"
msgstr ""
"Der angegebene Pfad scheint nicht zu existieren. Soll dieser inkorrekte Pfad "
"hinzugefügt werden?"

#: src/sbackup/ui/configgui.py:820
msgid "Save configuration as..."
msgstr "Konfiguration speichern unter..."

#: src/sbackup/ui/configgui.py:887
msgid ""
"A backup process is now executed in the background.\n"
"\n"
"You can monitor the progress of the backup by means of the status indicator "
"displayed in the notification area."
msgstr ""
"Ein Sicherungsvorgang wird im Hintergrund ausgeführt.\n"
"\n"
"Sie können den Fortschritt der Sicherung mit Hilfe des Statusindikators im "
"Benachrichtigungsbereich überwachen."

#: src/sbackup/ui/configgui.py:888
msgid "Backup process started"
msgstr "Sicherungsvorgang gestartet"

#: src/sbackup/ui/configgui.py:893 src/sbackup/ui/configgui.py:1661
#: src/sbackup/ui/configgui.py:2038
#, python-format
msgid "Unexpected dialog response: %s"
msgstr "Unerwartete Dialog Antwort: %s"

#: src/sbackup/ui/configgui.py:967
msgid "Include file..."
msgstr "Datei hinzufügen..."

#: src/sbackup/ui/configgui.py:974 src/sbackup/ui/configgui.py:1029
msgid "All files"
msgstr "Alle Dateien"

#: src/sbackup/ui/configgui.py:994
msgid "Include folder..."
msgstr "Ordner hinzufügen..."

#: src/sbackup/ui/configgui.py:1022
msgid "Exclude file..."
msgstr "Datei ausschliessen..."

#: src/sbackup/ui/configgui.py:1045
msgid "Exclude folder..."
msgstr "Ordner ausschliessen..."

#: src/sbackup/ui/configgui.py:1310
msgid "Configuration has changed"
msgstr "Konfiguration wurde geändert"

#: src/sbackup/ui/configgui.py:1311
msgid ""
"There are unsaved modifications. Please save the configuration or revert "
"these changes before testing the mail settings."
msgstr ""
"Es gibt ungesicherte Änderungen. Bitte sichere die Konfiguration oder mache "
"die Änderungen rückgängig um die E-Mail-Einstellungen zu testen."

#: src/sbackup/ui/configgui.py:1317 src/sbackup/ui/configgui.py:1323
msgid "Test mail settings"
msgstr "Testen der Einstellungen für E-Mail"

#: src/sbackup/ui/configgui.py:1318
msgid "The test failed with following output:"
msgstr "Der Test schlug mit folgender Ausgabe fehl:"

#: src/sbackup/ui/configgui.py:1324
msgid "The test was successful."
msgstr "Der Test war erfolgreich."

#: src/sbackup/ui/configgui.py:1407 src/sbackup/ui/configgui.py:1450
#, python-format
msgid ""
"The given expression contains unsupported characters ('%s'). Currently it is "
"not possible to use these characters in exclude expressions."
msgstr ""
"Der übergebene Ausdruck enthält nicht unterstützte Zeichen ('%s'). Es ist "
"zur Zeit nicht möglich diese Zeichen in 'Nicht Sichern'-Ausdrücken zu "
"verwenden."

#: src/sbackup/ui/configgui.py:1410 src/sbackup/ui/configgui.py:1453
msgid "Unsupported character"
msgstr "Nicht unterstütztes Zeichen"

#: src/sbackup/ui/configgui.py:1621
msgid "Connect to remote destination"
msgstr "Verbinde mit entferntem Ziel"

#: src/sbackup/ui/configgui.py:1669
msgid "Mount was sucessful (no errors)"
msgstr "Einhängen war erfolgreich (keine Fehler)"

#: src/sbackup/ui/configgui.py:1680
msgid "Unable to mount host"
msgstr "Einhängen des Servers fehlgeschlagen"

#: src/sbackup/ui/configgui.py:1689
msgid "Umount was sucessful (no errors)"
msgstr "Aushängen war erfolgreich (keine Fehler)"

#: src/sbackup/ui/configgui.py:1699
msgid "Unable to unmount host"
msgstr "unmounten des Ziels fehlgeschlagen"

#: src/sbackup/ui/configgui.py:1729
msgid "Perfom tests on remote host"
msgstr "Führe Tests auf entferntem Computer durch"

#: src/sbackup/ui/configgui.py:1742
msgid "Unable to access remote destination"
msgstr "Zugriff auf entfernten Server erfolglos"

#: src/sbackup/ui/configgui.py:1746
msgid "All tests passed"
msgstr "Alle Tests erfolgreich abgeschlossen"

#: src/sbackup/ui/configgui.py:1910
msgid ""
"The given name of the new profile is empty. Please enter a valid profile "
"name."
msgstr ""
"Der übergebene Profilname ist leer. Bitte einen gültigen Profilnamen "
"eingeben."

#: src/sbackup/ui/configgui.py:1911 src/sbackup/ui/configgui.py:1918
msgid "Profile name not valid"
msgstr "Profilname nicht gültig"

#: src/sbackup/ui/configgui.py:1917
msgid ""
"The given name of the new profile already exists. Please enter another name."
msgstr ""
"Der übergebene Profilname wird bereits verwendet. Bitte einen anderen "
"Profilnamen eingeben."

#: src/sbackup/ui/configgui.py:1919
msgid "Renaming of profiles is not supported."
msgstr "Das Umbenennen von Profilen wird nicht unterstützt."

#: src/sbackup/ui/configgui.py:1949
#, python-format
msgid ""
"<b>Delete configuration profile?</b>\n"
"\n"
"You are trying to remove a configuration profile. You will not be able to "
"restore it. If you are not sure, use the 'enable|disable' functionality "
"instead.\n"
"\n"
"Do you really want to delete the profile '%(name)s'?"
msgstr ""
"<b>Lösche Konfigurationsdatei?</b>\n"
"\n"
"Sie versuchen eine Konfigurationsprofil zu löschen. Rückgängigmachen der "
"Aktion ist unmöglich. Wenn sie nicht sicher sind, nutzen sie bitte "
"alternativ die \"aktivieren|deaktivieren\" Funktion.\n"
"\n"
"Möchten sie das Profil '%(name)s' wirklich löschen?"

#: src/sbackup/ui/configgui.py:2022
#, python-format
msgid ""
"<big><b>Set default values for current profile?</b></big>\n"
"This will restore the default values for the profile currently edited: "
"'%s'.\n"
"\n"
"These predefined settings are recommended for most users. Check whether they "
"are appropriate for your use before saving the changed configuration."
msgstr ""
"<big><b>Standardwerte für das aktuelle Profil setzen?</b></big>\n"
"Es werden die Standardwerte für das derzeitig bearbeitete Profil '%s' wieder "
"hergestellt.\n"
"\n"
"Diese vordefinierten Einstellungen sind für die meisten Anwender empfohlen. "
"Vor dem Speichern der geänderten Konfiguration sollte überprüft werden, ob "
"diese Einstellungen passend für den konkreten Anwendungsfall sind."

#: src/sbackup/ui/configgui.py:2032
msgid "Default settings are being applied."
msgstr "Standardwerte werden gesetzt."

#: src/sbackup/ui/configgui.py:2057
msgid ""
"<b>Unable to remove default profile</b>\n"
"\n"
"The default profile cannot be removed. In the case you want to use just a "
"single profile, please set up the default profile accordingly."
msgstr ""
"<b>Löschen des Standardprofils nicht möglich</b>\n"
"\n"
"Das Standardprofil kann nicht gelöscht werden. Wenn sie nur ein einziges "
"Profil nutzen wollen konfigurieren sie bitte das Standardprofil entsprechend."

#: src/sbackup/ui/configgui.py:2071
msgid ""
"<b>Unable to remove default profile</b>\n"
"\n"
"The default profile cannot be disabled. In the case you want to use just a "
"single profile, please set up the default profile accordingly."
msgstr ""
"<b>Löschen des Standardprofils nicht möglich</b>\n"
"\n"
"Das Standardprofil kann nicht deaktiviert werden. Wenn sie nur ein einziges "
"Profil nutzen wollen konfigurieren sie bitte das Standardprofil entsprechend."

#: src/sbackup/ui/configgui.py:2085
msgid ""
"<b>No backup profile found.</b>\n"
"\n"
"No default profile was found. You are probably running Simple Backup for the "
"first time. A backup profile using default values was created.\n"
"\n"
"Please modify the settings according to your needs and save the "
"configuration in order to use it."
msgstr ""
"<b>Kein Backupprofil gefunden.</b>\n"
"\n"
"Es wurde kein Standardprofil gefunden. Sie haben Simple Backup vermutlich "
"zum ersten mal gestartet. Ein Backup Profil mit Standardwerten wurde "
"erstellt.\n"
"\n"
"Bitte passen sie die Werte an ihre Bedürfnisse an und speichern sie das "
"Profil um es anschließend nutzen zu können."

#: src/sbackup/ui/configgui.py:2098
msgid "Please select a profile."
msgstr "Bitte ein Profil wählen."

#: src/sbackup/ui/indicator_core.py:117
msgid "there was a problem initializing the pynotify module"
msgstr "Es gab ein Problem beim Laden des pynotify Modul."

#: src/sbackup/ui/indicator_core.py:148 src/sbackup/ui/indicator_core.py:197
#: src/sbackup/ui/indicator_core.py:225 src/sbackup/ui/indicator_core.py:247
#, python-format
msgid "Connection to notification-daemon failed: %s"
msgstr "Verbindung zu Benachrichtigungsdienst fehlgeschlagen: %s"

#: src/sbackup/ui/indicator_core.py:310
msgid "Simple Backup"
msgstr "Simple Backup"

#: src/sbackup/ui/indicator_core.py:316
msgid "Show message windows"
msgstr "Dialogfenster anzeigen"

#: src/sbackup/ui/indicator_core.py:358 src/sbackup/ui/indicator_core.py:816
msgid "Cancel Backup"
msgstr "Sicherung abbrechen"

#: src/sbackup/ui/indicator_core.py:420
msgid "Connection to D-Bus service lost."
msgstr "Verbindung zu D-Bus Dienst verloren."

#: src/sbackup/ui/indicator_core.py:445
msgid "re-connection was successful"
msgstr "Verbindung wiederhergestellt"

#: src/sbackup/ui/indicator_core.py:484
msgid ""
"No backup in progress and connection to D-Bus service lost. Simple Backup "
"Indicator is being terminated."
msgstr ""
"Verbindung zum D-Bus Dienst wurde unterbrochen und es findet keine Sicherung "
"statt. Simple Backup Statusanzeige wird beendet."

#: src/sbackup/ui/indicator_core.py:513
msgid "Starting backup session"
msgstr "Sicherungsvorgang wird gestartet"

#: src/sbackup/ui/indicator_core.py:527
msgid "Ending Backup Session"
msgstr "Sicherungsvorgang wird beendet"

#: src/sbackup/ui/indicator_core.py:540
#, python-format
msgid "Unknown D-Bus event `%s` received."
msgstr "Unbekanntes D-Bus Ereignis `%s` erhalten."

#: src/sbackup/ui/indicator_core.py:581
msgid "Try again"
msgstr "Erneut versuchen"

#: src/sbackup/ui/indicator_core.py:651
msgid ""
"Attempt of starting another instance of Simple Backup while this one is "
"already running."
msgstr ""
"Es wurde versucht eine weitere Instanz von Simple Backup zu starten obwohl "
"bereits diese Instanz läuft."

#: src/sbackup/ui/indicator_core.py:661
#, python-format
msgid "Unable to present window: %s"
msgstr "Fenster konnte nicht angezeigt werden: %s"

#: src/sbackup/ui/indicator_core.py:677
#, python-format
msgid "Do you really want to cancel the backup process of profile '%s'?"
msgstr ""
"Soll der Sicherungsvorgang des Profils '%s' wirklich abgebrochen werden?"

#: src/sbackup/ui/indicator_core.py:681
msgid "Cancel running backup process?"
msgstr "Laufenden Sicherungsvorgang abbrechen?"

#: src/sbackup/ui/indicator_core.py:698
msgid "Unable to cancel backup process."
msgstr "Sicherungsvorgang konnte nicht abgebrochen werden."

#: src/sbackup/ui/indicator_core.py:760
#, python-format
msgid "Profile: %s"
msgstr "Profil: %s"

#: src/sbackup/ui/indicator_core.py:761
#, python-format
msgid "Size of backup: %s"
msgstr "Größe der Sicherung: %s"

#: src/sbackup/ui/indicator_core.py:762
#, python-format
msgid "%.1f%% processed"
msgstr "%.1f%% erledigt"

#: src/sbackup/ui/indicator_core.py:763
#, python-format
msgid "Remaining time: %s"
msgstr "Verbleibende Zeit: %s"

#: src/sbackup/ui/indicator_core.py:809
#, python-format
msgid "PID of backup process being canceled: %s"
msgstr "PID des abzubrechenden Sicherungsvorgangs: %s"

#: src/sbackup/ui/indicator_core.py:814
#, python-format
msgid "Unable to send signal to process %s"
msgstr "Konnte kein Signal an Prozess %s senden"

#: src/sbackup/ui/indicator_core.py:815
#, python-format
msgid "Sending signal using gksu to process %s"
msgstr "Sende Signal mittels gksu an Prozess %s"

#: src/sbackup/ui/indicator_core.py:819
#, python-format
msgid "Sending signal using gksu to process %s failed"
msgstr "Senden des Signals mittels gksu an Prozess %s fehlgeschlagen"

#: src/sbackup/ui/indicator_core.py:854
#, python-format
msgid ""
"<b>Unable to find specified target directory</b>\n"
"\n"
"The specified target directory '%s' was not found.\n"
"\n"
msgstr ""
"<b>Angegebener Zielordner nicht verfügbar</b>\n"
"\n"
"Der angegebene Pfad '%s' kann nicht gefunden werden.\n"
"\n"

#: src/sbackup/ui/indicator_core.py:855
#, python-format
msgid ""
"You can try to use the specified target again or cancel the profile "
"execution. The specified destination is automatically used in %s seconds."
msgstr ""
"Sie können erneut versuchen das festgelegt Sicherungsziel zu verwenden oder "
"den Sicherungsvorgang abbrechen. Die festgelegte Sicherung wird in %s "
"Sekunden automatisch erneut verwendet."

#: src/sbackup/ui/indicator_core.py:882 src/sbackup/ui/indicator_core.py:924
#: src/sbackup/ui/indicator_core.py:942 src/sbackup/ui/indicator_core.py:950
#: src/sbackup/ui/indicator_core.py:967
msgid "unknown"
msgstr "unbekannt"

#: src/sbackup/ui/indicator_core.py:903
msgid "less than 1 minute"
msgstr "weniger als 1 Minute"

#: src/sbackup/ui/indicator_core.py:905
msgid "about 2 minutes"
msgstr "ungefähr 2 Minuten"

#: src/sbackup/ui/indicator_core.py:907
msgid "about 3 minutes"
msgstr "ungefähr 3 Minuten"

#: src/sbackup/ui/indicator_core.py:909
msgid "about 4 minutes"
msgstr "ungefähr 4 Minuten"

#: src/sbackup/ui/indicator_core.py:911
msgid "about 5 minutes"
msgstr "ungefähr 5 Minuten"

#: src/sbackup/ui/indicator_core.py:913
#, python-format
msgid "about %.0f minutes"
msgstr "ungefähr %.0f Minuten"

#: src/sbackup/ui/indicator_core.py:923
msgid "In progress"
msgstr "Vorgang läuft"

#: src/sbackup/ui/indicator_core.py:933 src/sbackup/ui/indicator_core.py:959
msgid "finished"
msgstr "Fertiggestellt"

#: src/sbackup/ui/indicator_core.py:941
msgid "Progress: unknown"
msgstr "Fortschritt: unbekannt"

#: src/sbackup/ui/indicator_core.py:948
msgid "Backup is being prepared"
msgstr "Sicherung wird vorbereitet"

#: src/sbackup/ui/indicator_core.py:949
msgid "Collecting file info"
msgstr "Dateiinformationen sammeln"

#: src/sbackup/ui/indicator_core.py:958
msgid "Progress: canceled"
msgstr "Fortschritt: abgebrochen"

#: src/sbackup/ui/indicator_core.py:980
msgid "An error occurred"
msgstr "Ein Fehler trat auf"

#: src/sbackup/ui/indicator_core.py:1013
msgid "Another `Simple Backup Indicator` is already running."
msgstr "Eine andere `Simple Backup Statusanzeige` läuft bereits."

#: src/sbackup/ui/indicator_core.py:1037
#, python-format
msgid "Initialization of GTK+ failed: %s"
msgstr "Initialisierung von GTK+ fehlgeschlagen: %s"

#: src/sbackup/ui/misc.py:294
#, python-format
msgid "%s   (Administrator mode)"
msgstr "%s (Administrator-Modus)"

#: src/sbackup/ui/misc.py:324
#, python-format
msgid ""
"An uncaught error occurred. Close this message window and restart the "
"application.\n"
"\n"
"Please report this error on https://bugs.launchpad.net/sbackup.\n"
"\n"
"%s"
msgstr ""
"Ein unbekannter Fehler ist aufgetreten. Schließen Sie dieses Fenster und "
"starten Sie die Anwendung neu.\n"
"\n"
"Bitte melden Sie diesen Fehler unter: https://bugs.launchpad.net/sbackup.\n"
"\n"
"%s"

#: src/sbackup/ui/misc.py:325
msgid "Sorry, this should not have happened"
msgstr "Entschuldigung, das hätte nicht passieren dürfen"

#: src/sbackup/ui/restoregui.py:78
msgid "Restore..."
msgstr "Wiederherstellen..."

#: src/sbackup/ui/restoregui.py:79 data/ui/sbackup-restore.glade:765
msgid "Restore as..."
msgstr "Wiederherstellen unter..."

#: src/sbackup/ui/restoregui.py:80
msgid "Revert..."
msgstr "Rückgängig machen..."

#: src/sbackup/ui/restoregui.py:81 data/ui/sbackup-restore.glade:797
msgid "Revert as..."
msgstr "Rückgängig machen unter..."

#: src/sbackup/ui/restoregui.py:128 data/ui/sbackup-restore.glade:111
#: data/ui/sbackup-restore.glade:511
msgid "n.a."
msgstr "k.A."

#: src/sbackup/ui/restoregui.py:146 src/sbackup/ui/restoregui.py:163
msgid "Snapshots"
msgstr "Sicherungen"

#: src/sbackup/ui/restoregui.py:147
msgid "Version"
msgstr "Version"

#: src/sbackup/ui/restoregui.py:154 data/ui/sbackup-config.glade:4063
msgid "Path"
msgstr "Pfad"

#: src/sbackup/ui/restoregui.py:159
msgid "State"
msgstr "Status"

#: src/sbackup/ui/restoregui.py:187
msgid "Connect to destination..."
msgstr "Verbinde mit Zielverzeichnis..."

#: src/sbackup/ui/restoregui.py:211
msgid "Specified path does not exist"
msgstr "Der angegebene Pfad existiert nicht"

#: src/sbackup/ui/restoregui.py:257
msgid "Ready"
msgstr "Fertig"

#: src/sbackup/ui/restoregui.py:371
msgid "No destination specified"
msgstr "Kein Sicherungsziel angegeben"

#: src/sbackup/ui/restoregui.py:388
msgid "Choose a source folder"
msgstr "Wählen Sie einen Quellordner"

#: src/sbackup/ui/restoregui.py:405
msgid "Reading snapshots..."
msgstr "Einlesen der Sicherungen..."

#: src/sbackup/ui/restoregui.py:428
msgid "Reading directory content..."
msgstr "Einlesen des Verzeichnisinhalts..."

#: src/sbackup/ui/restoregui.py:458 src/sbackup/ui/restoregui.py:496
msgid "Loading ..."
msgstr "Lade ..."

#: src/sbackup/ui/restoregui.py:539
msgid "Reading files from snapshot..."
msgstr "Einlesen der Dateien der Sicherung..."

#: src/sbackup/ui/restoregui.py:552
msgid "Simple Backup restore error"
msgstr "Simple Backup Wiederherstellungsfehler"

#: src/sbackup/ui/restoregui.py:553
msgid "An error occurred while reading snapshot"
msgstr "Während des Einlesen der Sicherung ist ein Fehler aufgetreten"

#: src/sbackup/ui/restoregui.py:557
msgid "This snapshot seems empty."
msgstr "Diese Sicherung scheint leer zu sein."

#: src/sbackup/ui/restoregui.py:576
msgid "Reading backup snapshot..."
msgstr "Lese Sicherungsschnappschuss"

#: src/sbackup/ui/restoregui.py:599
msgid "No backups found for this day."
msgstr "Keine Sicherungen für dieses Datum gefunden."

#: src/sbackup/ui/restoregui.py:614 src/sbackup/ui/restoregui.py:771
#, python-format
msgid ""
"Snapshot version is not supported (Only %(supportedversion)s is supported). "
"Version '%(currentversion)s' found."
msgstr ""

#: src/sbackup/ui/restoregui.py:643
msgid "Select restore location"
msgstr "Ort für die Wiederherstellung auswählen"

#: src/sbackup/ui/restoregui.py:662
#, python-format
msgid "Do you really want to revert '%s'?"
msgstr "Sollen die Änderungen an '%s' wirklich rückgängig gemacht werden?"

#: src/sbackup/ui/restoregui.py:676
msgid "Select revert location"
msgstr "Auswahl eines Verzeichnisses um Änderungen rückgängig zu machen"

#: src/sbackup/ui/restoregui.py:685
#, python-format
msgid "Do you really want to revert '%(source)s' to '%(dir)s'?"
msgstr ""
"\"Sollen die Änderungen an '%(source)s' wirklich nach '%(dir)s' rückgängig "
"gemacht werden?\""

#: src/sbackup/ui/restoregui.py:763
msgid "Reading snapshot..."
msgstr "Einlesen der Sicherung..."

#: src/sbackup/ui/restoregui.py:782
#, python-format
msgid ""
"Deleting the selected snapshot `%s` will remove your backup for this "
"particular point in time. You cannot undo this operation.\n"
"\n"
"Are you sure that you want to remove the snapshot permanently?"
msgstr ""
"Wenn sie die gewählte Sicherungsdatei '%s' löschen, geht die Sicherung für "
"diesen Zeitpunkt verloren. Sie können die Aktion nicht rückgängig machen.\n"
"\n"
"Sind Sie sicher, dass Sie die Sicherungsdatei endgültig löschen wollen?"

#: src/sbackup/ui/restoregui.py:786
msgid "Do you really want to remove snapshot?"
msgstr "Möchten Sie diese Sicherung wirklich entfernen?"

#: src/sbackup/ui/restoregui.py:795
#, python-format
msgid ""
"While attempting to delete snapshot the following error occurred:\n"
"%s"
msgstr ""
"Beim Löschen der Sicherung trat folgender Fehler auf:\n"
"%s"

#: src/sbackup/ui/restoregui.py:798
msgid "Unable to delete snapshot"
msgstr "Sicherung konnte nicht gelöscht werden"

#: src/sbackup/ui/restoregui.py:804
#, python-format
msgid ""
"The selected snapshot '%s' is referenced by more recent snapshots as base "
"snapshot.\n"
"\n"
"Remove all of these child snapshots in order to delete this snapshot."
msgstr ""
"Die gewählte Sicherungsdatei '%s' wird von aktuelleren Sicherungen als "
"Grundlage verwendet.\n"
"\n"
"Löschen Sie alle abhängigen Sicherungen, um diese Sicherungsdatei löschen zu "
"können."

#: src/sbackup/ui/restoregui.py:806
msgid "Unable to remove snapshot"
msgstr "Konnte Sicherung nicht entfernen."

#: src/sbackup/ui/restoregui.py:814
msgid "Termination in progress"
msgstr "Aktion wird abgebrochen"

#: src/sbackup/ui/restoregui.py:830 src/sbackup/ui/restoregui.py:836
#: src/sbackup/ui/restoregui.py:842 src/sbackup/ui/restoregui.py:848
#: data/ui/sbackup-restore.glade:959
msgid "Simple Backup restoration"
msgstr "Simple Backup Wiederherstellung"

#: src/sbackup/ui/restoregui.py:831 src/sbackup/ui/restoregui.py:837
msgid "<b>Restoring of selected files</b>"
msgstr "<b>Wiederherstellung der ausgewählten Dateien</b>"

#: src/sbackup/ui/restoregui.py:832
#, python-format
msgid "Restoring of <tt>'%s'</tt> is in progress."
msgstr "Die Wiederherstellung von <tt>'%s'</tt> wird durchgeführt."

#: src/sbackup/ui/restoregui.py:833
#, python-format
msgid "Restoring of <tt>'%s'</tt> was successful."
msgstr "Wiederherstellung von <tt>'%s'</tt> war erfolgreich."

#: src/sbackup/ui/restoregui.py:834
#, python-format
msgid ""
"Restoring of <tt>'%s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Die Wiederherstellung von <tt>'%s'</tt> schlug fehl.\n"
"\n"
"Folgender Fehler trat auf:\n"

#: src/sbackup/ui/restoregui.py:838
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> is in progress."
msgstr ""
"Wiederherstellung von <tt>'%(source)s'</tt>\n"
"nach <tt>'%(dirname)s'</tt> wird ausgeführt."

#: src/sbackup/ui/restoregui.py:839
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was successful."
msgstr ""
"Wiederherstellung von <tt>'%(source)s'</tt>\n"
"nach <tt>'%(dirname)s'</tt> war erfolgreich."

#: src/sbackup/ui/restoregui.py:840
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Die Wiederherstellung von <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> schlug fehl.\n"
"\n"
"Folgender Fehler trat auf::\n"

#: src/sbackup/ui/restoregui.py:843 src/sbackup/ui/restoregui.py:849
msgid "<b>Reverting selected files</b>"
msgstr "<b>Änderungen an ausgewählten Dateien werden rückgängig gemacht</b>"

#: src/sbackup/ui/restoregui.py:844
#, python-format
msgid "Reverting of <tt>'%s'</tt> is in progress.\n"
msgstr "Rückgängig machen von <tt>'%s'</tt> wird durchgeführt.\n"

#: src/sbackup/ui/restoregui.py:845
#, python-format
msgid "Reverting of <tt>'%s'</tt> was successful."
msgstr "Rückgängig machen von <tt>'%s'</tt> war erfolgreich."

#: src/sbackup/ui/restoregui.py:846
#, python-format
msgid ""
"Reverting of <tt>'%s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Die Wiederherstellung von <tt>'%s'</tt> war nicht erfolgreich.\n"
"\n"
"Es trat folgender Fehler auf:\n"

#: src/sbackup/ui/restoregui.py:850
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> is in progress."
msgstr ""
"Rückgängig machen von <tt>'%(source)s'</tt>\n"
"nach <tt>'%(dirname)s'</tt> wird durchgeführt."

#: src/sbackup/ui/restoregui.py:851
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was successful."
msgstr ""
"Rückgängig machen von <tt>'%(source)s'</tt>\n"
"nach <tt>'%(dirname)s'</tt> war erfolgreich."

#: src/sbackup/ui/restoregui.py:852
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""
"Die Wiederherstellung von <tt>'%(source)s'</tt> nach <tt>'%(dirname)s'</tt> "
"war nicht erfolgreich.\n"
"\n"
"Es trat folgender Fehler auf:\n"

#: src/sbackup/util/__init__.py:439
#, python-format
msgid "%(mb)d MiB %(kb)d KiB"
msgstr "%(mb)d MiB %(kb)d KiB"

#: src/sbackup/util/__init__.py:442
#, python-format
msgid "%(mb)d MiB %(kb)d KiB %(bytes)d"
msgstr "%(mb)d MiB %(kb)d KiB %(bytes)d"

#: src/sbackup/util/__init__.py:447
#, python-format
msgid "%(mb)d MB %(kb)d kB"
msgstr "%(mb)d MB %(kb)d kB"

#: src/sbackup/util/__init__.py:450
#, python-format
msgid "%(mb)d MB %(kb)d kB %(bytes)d"
msgstr "%(mb)d MB %(kb)d kB %(bytes)d"

#: src/sbackup/util/filecollect.py:335
#, python-format
msgid "File '%(file)s' is not accessable with error '%(error)s'."
msgstr ""
"Auf Datei '%(file)s' kann nicht zugegriffen werden. Fehler '%(error)s'."

#: src/sbackup/util/filecollect.py:351
#, python-format
msgid ""
"File '%(file)s' cannot be opened for read access. Operation timed out."
msgstr ""
"Datei '%(file)s' kann nicht zum Lesen geöffnet werden. Zeitüberschreitung "
"beim Öffnen."

#: src/sbackup/util/filecollect.py:355
#, python-format
msgid ""
"File '%(file)s' cannot be opened for read access with error '%(error)s'."
msgstr ""
"Datei '%(file)s' kann nicht zum Lesen geöffnet werden. Fehler '%(error)s'."

#: src/sbackup/util/filecollect.py:372
#, python-format
msgid "Symbolic link '%(path)s' -> '%(ln_target)s' is a circular symlink."
msgstr ""
"Symbolische Verknüpfung '%(path)s' -> '%(ln_target)s' erzeugt einen "
"Kreisbezug."

#: src/sbackup/util/filecollect.py:388
#, python-format
msgid "File '%(file)s' is backup's target directory."
msgstr "Pfad '%(file)s' ist das Zielverzeichnis der Sicherung."

#: src/sbackup/util/filecollect.py:393
#, python-format
msgid "Path '%(file)s' defined in excludes list."
msgstr "Pfad '%(file)s' ist in der 'Nicht Sichern'-Liste vorhanden."

#: src/sbackup/util/filecollect.py:401
#, python-format
msgid "File '%(file)s' matches regular expression '%(regex)s'."
msgstr "Pfad '%(file)s' erfüllt den Regulären Ausdruck '%(regex)s'."

#: src/sbackup/util/filecollect.py:419
#, python-format
msgid ""
"File '%(file)s' exceeds maximum file size ( %(filesize)s > %(maxsize)s)."
msgstr ""
"Datei '%(file)s' überschreitet die maximale Dateigröße  ( %(filesize)s > "
"%(maxsize)s)."

#: src/sbackup/util/filecollect.py:497
#, python-format
msgid "Error while checking directory '%(dir)s': %(error)s."
msgstr "Fehler beim Testen des Verzeichnisses '%(dir)s': %(error)s."

#: src/sbackup/util/filecollect.py:548
msgid "Empty regular expression found. Skipped."
msgstr "Leerer Regulärer Ausdruck gefunden. Wird ausgelassen."

#: src/sbackup/util/filecollect.py:554
#, python-format
msgid "Invalid regular expression ('%s') found. Skipped."
msgstr "Ungültiger Regulärer Ausdruck ('%s') gefunden. Wird ausgelassen."

#: src/sbackup/util/filecollect.py:573
msgid "No directories to backup defined."
msgstr "Keine Verzeichnisse zum Sichern festgelegt."

#: src/sbackup/util/lock.py:76
msgid "Another application instance is already running."
msgstr "Eine andere Instanz des Programms läuft bereits."

#: src/sbackup/util/lock.py:78
msgid "Invalid lock file found. Is being removed."
msgstr "Ungültige Lock-Datei gefunden. Wird entfernt."

#: src/sbackup/util/lock.py:128 src/sbackup/util/lock.py:142
#, python-format
msgid "Unable to remove lock file: %s"
msgstr "Lock-Datei konnte nicht entfernt werden: %s"

#: src/sbackup/util/lock.py:132 src/sbackup/util/lock.py:144
msgid "Unable to remove lock file: File not found."
msgstr ""
"Die Lock-Datei konnte nicht entfernt werden, da die Datei nicht gefunden "
"wurde."

#: data/ui/sbackup-config.glade:11
msgid "Exclude file type"
msgstr "Dateityp ausschließen"

#: data/ui/sbackup-config.glade:26
msgid "Standard file types:"
msgstr "Standard Dateitypen:"

#: data/ui/sbackup-config.glade:63
msgid "Custom defined file type with "
msgstr "Selbstdefinierter Dateityp mit "

#: data/ui/sbackup-config.glade:93
msgid "file extension"
msgstr "Dateierweiterung"

#: data/ui/sbackup-config.glade:163
msgid "Exclude by regex"
msgstr "Ausschließen mittels Suchmuster (regulärer Ausdruck)"

#: data/ui/sbackup-config.glade:180
msgid ""
"Enter a regular expression.\n"
"Files and directories matching this expression will be excluded from backup."
msgstr ""
"Geben Sie einen regulären Ausdruck an.\n"
"Dateien und Ordner, die diesem Ausdruck entsprechen, werden von der "
"Sicherung ausgeschlossen."

#: data/ui/sbackup-config.glade:257
msgid "Enter the remote target to include"
msgstr ""
"Geben Sie einen entfernten Ordner/Datei an, der gesichert werden soll"

#: data/ui/sbackup-config.glade:278
msgid "Choose a plugin to get the format"
msgstr "Wählen Sie ein Plugin um das Format zu bestimmen"

#: data/ui/sbackup-config.glade:295
msgid "Choose your plugin :"
msgstr "Wählen Sie Ihr Plugin:"

#: data/ui/sbackup-config.glade:367
msgid "Check"
msgstr "Prüfen"

#: data/ui/sbackup-config.glade:479
msgid ""
"<b>Save changed configuration?</b>\n"
"\n"
"The configuration has changed. If you want to use the modified "
"configuration, you have to save it.\n"
"\n"
"Do you want to save the configuration now?"
msgstr ""
"<b>Geänderte Konfiguration speichern?</b>\n"
"\n"
"Die Konfiguration wurde geändert. Soll die geänderte Konfiguration verwendet "
"werden, so muss sie gespeichert werden.\n"
"\n"
"Soll die Konfiguration jetzt gespeichert werden?"

#: data/ui/sbackup-config.glade:572
msgid "Configuration Profile Manager"
msgstr "Profilverwaltung"

#: data/ui/sbackup-config.glade:594
msgid ""
"You can set up multiple configuration profiles which are processed when "
"performing a backup. Each profile has its own set of settings including "
"backup destination, backup format etc."
msgstr ""
"Sie können mehrere Profile einrichten, die ausgeführt werden, wenn eine "
"Sicherung durchgeführt wird. Jedes Profil hat seine eigenen Einstellungen, "
"die Sicherungsziel, Format der Sicherung etc. enthalten."

#: data/ui/sbackup-config.glade:613
msgid "<b>Configuration profiles</b>"
msgstr "Einstellungsprofile"

#: data/ui/sbackup-config.glade:785
msgid ""
"<b>Add new profile</b>\n"
"\n"
"Please enter the new profile name and set the according checkbox in order to "
"enable resp. disable it."
msgstr ""
"<b>Hinzufügen eines Profils</b>\n"
"\n"
"Bitte den Namen des neuen Profils angeben und festlegen ob das Profil aktiv "
"bzw. inaktiv sein soll."

#: data/ui/sbackup-config.glade:810
msgid "Profile name"
msgstr "Profilname"

#: data/ui/sbackup-config.glade:836
msgid "Enabled"
msgstr "Aktiviert"

#: data/ui/sbackup-config.glade:915 data/ui/sbackup-restore.glade:7
msgid "Simple Backup Suite"
msgstr "Simple Backup Suite"

#: data/ui/sbackup-config.glade:932
msgid "_File"
msgstr "_Datei"

#: data/ui/sbackup-config.glade:971
msgid "Save as..."
msgstr "Speichern unter..."

#: data/ui/sbackup-config.glade:1008
msgid "_Tools"
msgstr "_Werkzeuge"

#: data/ui/sbackup-config.glade:1016 data/ui/sbackup-config.glade:1140
msgid "Set default settings..."
msgstr "Standardwerte setzen..."

#: data/ui/sbackup-config.glade:1037
msgid "Profile Manager..."
msgstr "Profilverwaltung..."

#: data/ui/sbackup-config.glade:1058
msgid "Make backup now"
msgstr "Die Sicherung jetzt durchführen"

#: data/ui/sbackup-config.glade:1079
msgid "_Help"
msgstr "_Hilfe"

#: data/ui/sbackup-config.glade:1087
msgid "_View all help topics"
msgstr "_Hilfethemen"

#: data/ui/sbackup-config.glade:1103
msgid "_About this program"
msgstr "Info"

#: data/ui/sbackup-config.glade:1154
msgid "Reload configuration"
msgstr "Einstellungen neu laden"

#: data/ui/sbackup-config.glade:1168
msgid "Save configuration"
msgstr "Konfiguration speichern"

#: data/ui/sbackup-config.glade:1191
msgid "Make a backup now"
msgstr "Sicherung jetzt erstellen"

#: data/ui/sbackup-config.glade:1214
msgid "Open the profile manager"
msgstr "Profilverwaltung öffnen"

#: data/ui/sbackup-config.glade:1215
msgid "Profiles"
msgstr "Profile"

#: data/ui/sbackup-config.glade:1253
msgid ""
"none\n"
"gzip\n"
"bzip2"
msgstr ""
"none\n"
"gzip\n"
"bzip2"

#: data/ui/sbackup-config.glade:1271
msgid ""
"Compression format\n"
"Default is set to uncompressed backups."
msgstr ""
"Kompressionsformat\n"
"Der Standard sind unkomprimierte Sicherungen."

#: data/ui/sbackup-config.glade:1290 data/ui/sbackup-config.glade:1403
msgid ""
"You can split the snapshot to make backup on some filesystem that doesn't "
"support large files. This functionality can not be used if the backup is "
"compressed."
msgstr ""
"Die Sicherung kann in kleinere Dateien aufgeteilt werden, um Sicherung auf "
"Dateisystemen abzulegen, die keine beliebig großen Dateien unterstützen. "
"Diese Funktion kann nicht in Verbindung mit komprimierten Sicherungen "
"verwendet werden."

#: data/ui/sbackup-config.glade:1330
msgid "Do a full backup at least once every"
msgstr "Vollständige Sicherung mindestens alle"

#: data/ui/sbackup-config.glade:1339
msgid ""
"Unless a set number of days has passed since the last full backup, "
"incremental backups will be done."
msgstr ""
"Bis zur festgelegten Anzahl an Tagen seit der letzten vollständigen "
"Sicherung werden inkrementelle Sicherungen erstellt."

#: data/ui/sbackup-config.glade:1356 data/ui/sbackup-config.glade:3015
msgid "days"
msgstr "Tage"

#: data/ui/sbackup-config.glade:1370
msgid " "
msgstr " "

#: data/ui/sbackup-config.glade:1380 data/ui/sbackup-config.glade:2323
msgid "MiB"
msgstr "MiB"

#: data/ui/sbackup-config.glade:1405
msgid "Split backup archives into several chunks"
msgstr "Teile die Sicherungsarchive in mehrere Teile"

#: data/ui/sbackup-config.glade:1438 data/ui/sbackup-config.glade:2627
#: data/ui/sbackup-config.glade:2863 data/ui/sbackup-config.glade:3111
#: data/ui/sbackup-config.glade:3856
msgid "Help"
msgstr "Hilfe"

#: data/ui/sbackup-config.glade:1442 data/ui/sbackup-config.glade:2632
msgid "Show help topic about configuration GUI."
msgstr "Hilfe zu den Einstellungen mittels grafischer Oberfläche zeigen."

#: data/ui/sbackup-config.glade:1475
msgid "General"
msgstr "Allgemein"

#: data/ui/sbackup-config.glade:1495
msgid "<b>Included files and directories</b>"
msgstr "<b>Einbezogene Dateien und Verzeichnisse</b>"

#: data/ui/sbackup-config.glade:1570 data/ui/sbackup-config.glade:1818
#: data/ui/sbackup-config.glade:2023 data/ui/sbackup-config.glade:2181
msgid "Remove"
msgstr "Entfernen"

#: data/ui/sbackup-config.glade:1620 data/ui/sbackup-config.glade:1868
msgid "Add File"
msgstr "Datei hinzufügen"

#: data/ui/sbackup-config.glade:1671 data/ui/sbackup-config.glade:1919
msgid "Add Directory"
msgstr "Ordner hinzufügen"

#: data/ui/sbackup-config.glade:1718
msgid "Include"
msgstr "Zu sichernde Daten"

#: data/ui/sbackup-config.glade:1739
msgid "<b>Excluded files and directories</b>"
msgstr "<b>Ausgeschlossene Dateien und Verzeichnisse</b>"

#: data/ui/sbackup-config.glade:1952
msgid "Paths"
msgstr "Pfade"

#: data/ui/sbackup-config.glade:2074 data/ui/sbackup-config.glade:2232
msgid "Add"
msgstr "Hinzufügen"

#: data/ui/sbackup-config.glade:2109
msgid "File types"
msgstr "Dateitypen"

#: data/ui/sbackup-config.glade:2267
msgid ""
"Regular\n"
"Expressions"
msgstr ""
"Reguläre\n"
"Ausdrücke"

#: data/ui/sbackup-config.glade:2288
msgid "Do not backup files bigger than"
msgstr "Keine Dateien sichern, die größer sind als"

#: data/ui/sbackup-config.glade:2344
msgid "Follow symbolic links"
msgstr "Symbolischen Verknüpfungen folgen"

#: data/ui/sbackup-config.glade:2373
msgid "Others"
msgstr "Sonstige"

#: data/ui/sbackup-config.glade:2400
msgid "Exclude"
msgstr "Nicht Sichern"

#: data/ui/sbackup-config.glade:2421
msgid "Use default backup directory"
msgstr "Standardverzeichnis für Sicherungen verwenden"

#: data/ui/sbackup-config.glade:2446
msgid "/var/backup"
msgstr "/var/backup"

#: data/ui/sbackup-config.glade:2472
msgid "Use custom local backup directory"
msgstr "Benutzerdefiniertes lokales Sicherungs-Verzeichnis verwenden"

#: data/ui/sbackup-config.glade:2500
msgid "Select the destination folder"
msgstr "Zielverzeichnis auswählen"

#: data/ui/sbackup-config.glade:2526
msgid "Use a remote site"
msgstr "Einen entfernten Speicher verwenden"

#: data/ui/sbackup-config.glade:2568
msgid "ssh://username:password@example.com/remote/dir/"
msgstr "ssh://benutzername:kennwort@beispiel.com/entfernt/ordner/"

#: data/ui/sbackup-config.glade:2580
msgid "Connect..."
msgstr "Verbinde..."

#: data/ui/sbackup-config.glade:2672
msgid ""
"<i>The selected destination is not writeable with current permissions. "
"Backups cannot be stored there.</i>"
msgstr ""
"<i>Das ausgewählte Zielverzeichnis ist mit den derzeitigen Zugriffsrechten "
"nicht beschreibbar. Sicherungen können dort nicht abgelegt werden.</i>"

#: data/ui/sbackup-config.glade:2704
msgid "Destination"
msgstr "Zielverzeichnis"

#: data/ui/sbackup-config.glade:2725
msgid "_No scheduled backups"
msgstr "_Keine geplanten/automatischen Sicherungen"

#: data/ui/sbackup-config.glade:2742
msgid "_Simple"
msgstr "_Einfach"

#: data/ui/sbackup-config.glade:2747
msgid ""
"This option will make a backup not at a precise time but when the computer "
"is up. "
msgstr ""
"Mit dieser Einstellung wird die Sicherung nicht zu einer bestimmten Zeit "
"durchgeführt, sondern, wenn der Computer eingeschaltet ist. "

#: data/ui/sbackup-config.glade:2761
msgid "_Custom"
msgstr "_Benutzerdefiniert"

#: data/ui/sbackup-config.glade:2781
msgid "Do backups"
msgstr "Sicherungen erstellen"

#: data/ui/sbackup-config.glade:2798
msgid "Cron time definition"
msgstr "Cron-Ausdruck"

#: data/ui/sbackup-config.glade:2834
msgid ""
"hourly\n"
"daily\n"
"weekly\n"
"monthly"
msgstr ""
"Stündlich\n"
"Täglich\n"
"Wöchentlich\n"
"Monatlich"

#: data/ui/sbackup-config.glade:2867
msgid "Show help topic about scheduled backups."
msgstr "Hilfe zu geplanten Sicherungen anzeigen."

#: data/ui/sbackup-config.glade:2905
msgid ""
"<small>You can configure scheduled (i.e. automated) backups either simply by "
"choosing an interval or precisely by a custom cron definition. See \"man 5 "
"crontab\" for cron time definition format.</small>"
msgstr ""
"<small>Geplante/Zeitgesteuerte (d.h. automatische) Sicherungen können durch "
"das einfache Auswählen des gewünschten Intervalles oder durch die Festlegung "
"eines benutzerdefinierten Cron-Ausdruckes konfiguriert werden. Siehe \"man 5 "
"crontab\" für das Format der Cron-Ausdrücke.</small>"

#: data/ui/sbackup-config.glade:2937
msgid "Schedule"
msgstr "Zeitplan"

#: data/ui/sbackup-config.glade:2955
msgid "Enable purging of old backups"
msgstr "Löschen von alten Sicherungen einschalten"

#: data/ui/sbackup-config.glade:2983
msgid "Simple cut-off: Erase all backups older than"
msgstr "Einfaches Entfernen: Löschen aller Sicherungen älter als"

#: data/ui/sbackup-config.glade:3039
msgid "Logarithmic"
msgstr "Logarithmisches Entfernen"

#: data/ui/sbackup-config.glade:3065
msgid ""
"<small>Keep progressively less backups into the past:\n"
"Keep all backups from yesterday\n"
"Keep one backup per day from last week\n"
"Keep one backup per week from last month\n"
"Keep one backup per month from last year\n"
"Keep one backup per quarter from 2nd last year\n"
"Keep one backup per year further into past</small>"
msgstr ""
"<small>In die Vergangenheit weniger werdend behalten:\n"
"Eine Sicherung von gestern behalten\n"
"Eine Sicherung pro Tag aus der letzten Woche behalten\n"
"Eine Sicherung pro Woche aus dem letzten Monat behalten\n"
"Eine Sicherung pro Monat aus dem letzten Jahr behalten\n"
"Eine Sicherung pro Vierteljahr aus dem vorletzen Jahr behalten\n"
"Eine Sicherung pro Jahr aus jedem vorherigen Jahr behalten.</small>"

#: data/ui/sbackup-config.glade:3116
msgid "Show help topic about purging of backups."
msgstr "Hilfe zum Aufräumen von Sicherungen anzeigen."

#: data/ui/sbackup-config.glade:3152
msgid ""
"<small>Note: Additionally all incomplete and irrecoverable backups will be "
"erased as long as there is a complete backup snapshot made later on.</small>"
msgstr ""
"<small>Hinweis: Darüber hinaus werden alle unvollständigen und nicht "
"wiederherstellbaren Sicherungen gelöscht, sofern eine vollständige Sicherung "
"eines späteren Zeitpunktes verfügbar ist.</small>"

#: data/ui/sbackup-config.glade:3184
msgid "Purging"
msgstr "Aufräumen"

#: data/ui/sbackup-config.glade:3186
msgid "Cleaning old backups"
msgstr "Alte Sicherungen säubern"

#: data/ui/sbackup-config.glade:3209
msgid "<b>Logging</b>"
msgstr "<b>Protokollieren</b>"

#: data/ui/sbackup-config.glade:3234
msgid "Debug is just for debbuging purpose.Info is the recommended setting"
msgstr ""
"Die empfohlene Einstellung ist 'Info'. Die Einstellung 'Debug' ist für "
"Entwicklerzwecke vorgesehen."

#: data/ui/sbackup-config.glade:3236
msgid "Log level"
msgstr "Protokollierungsstufe"

#: data/ui/sbackup-config.glade:3248
msgid "Debug is just for debbuging purpose. Info is the recommended setting."
msgstr ""
"'Debug' dient der Fehlerbehebung. Die empfohlene Einstellung is 'Info'."

#: data/ui/sbackup-config.glade:3274
msgid "Log file directory"
msgstr "Verzeichnis der Protokolldatei"

#: data/ui/sbackup-config.glade:3320
msgid "<b>Report by mail</b>"
msgstr "<b>Bericht per E-Mail</b>"

#: data/ui/sbackup-config.glade:3350
msgid "From"
msgstr "Absender"

#: data/ui/sbackup-config.glade:3361
msgid "SMTP server"
msgstr "SMTP-Server"

#: data/ui/sbackup-config.glade:3375 data/ui/sbackup-config.glade:4053
msgid "Port"
msgstr "Portnummer"

#: data/ui/sbackup-config.glade:3391
msgid "To"
msgstr "An"

#: data/ui/sbackup-config.glade:3478
msgid "Use a username and password"
msgstr "Benutzername und Kennwort verwenden"

#: data/ui/sbackup-config.glade:3508 data/ui/sbackup-config.glade:4075
msgid "Username"
msgstr "Benutzername"

#: data/ui/sbackup-config.glade:3540 data/ui/sbackup-config.glade:4124
msgid "Password"
msgstr "Kennwort"

#: data/ui/sbackup-config.glade:3584
msgid "Use secure connection"
msgstr "Sichere Verbindung benutzen"

#: data/ui/sbackup-config.glade:3615
msgid "Choose a certificate file"
msgstr "Zertifikatsdatei auswählen"

#: data/ui/sbackup-config.glade:3629
msgid "Key"
msgstr "Schlüssel"

#: data/ui/sbackup-config.glade:3645
msgid "Certificate"
msgstr "Zertifikat"

#: data/ui/sbackup-config.glade:3659
msgid "Choose a key file"
msgstr "Schlüsseldatei auswählen"

#: data/ui/sbackup-config.glade:3731
msgid "Test _mail settings"
msgstr "Testen der _Mail Einstellungen"

#: data/ui/sbackup-config.glade:3772
msgid "Report"
msgstr "Berichte"

#: data/ui/sbackup-config.glade:3811
msgid "Warning"
msgstr "Achtung"

#: data/ui/sbackup-config.glade:3860
msgid "Show help topic about default values."
msgstr "Zeige das Hilfethema zu Standardwerten."

#: data/ui/sbackup-config.glade:3893
msgid "_Set"
msgstr "_Setzen"

#: data/ui/sbackup-config.glade:3935
msgid "Set remote target"
msgstr "Entferntes Ziel festlegen"

#: data/ui/sbackup-config.glade:3957
msgid "Type of service"
msgstr "Art des Dienstes"

#: data/ui/sbackup-config.glade:3997
msgid "Hostname"
msgstr "Rechnername"

#: data/ui/sbackup-config.glade:4027
msgid "<b>Details</b>"
msgstr "<b>Details</b>"

#: data/ui/sbackup-config.glade:4157
msgid "Show password"
msgstr "Passwort anzeigen"

#: data/ui/sbackup-config.glade:4217
msgid "_Connect"
msgstr "_Verbinden"

#: data/ui/sbackup-config.glade:4293
msgid "Make a full backup"
msgstr "Eine vollständige Sicherung durchführen"

#: data/ui/sbackup-legacy-restore.glade:7
msgid "Restore files/directories"
msgstr "Dateien/Verzeichnisse wiederherstellen"

#: data/ui/sbackup-legacy-restore.glade:25
msgid "<b>Restore Source Folder</b>"
msgstr "<b>Quellordner wiederherstellen</b>"

#: data/ui/sbackup-legacy-restore.glade:90
msgid "Available backups:"
msgstr "Verfügbare Datensicherungen:"

#: data/ui/sbackup-legacy-restore.glade:109
msgid ""
"Type in this box text like that:\n"
"\n"
"/home/user/folder - To use a local folder\n"
"ssh://user:password@machine:/remote/folder - To use a ssh location\n"
"ftp://user:password@machine:/remote/folder - To use a ftp location"
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:179
msgid "Use custom:"
msgstr "Eigene Einstellung verwenden:"

#: data/ui/sbackup-legacy-restore.glade:200
msgid "Use default:"
msgstr "Standard verwenden:"

#: data/ui/sbackup-legacy-restore.glade:241
msgid "<b>Files and Folders to restore</b>"
msgstr "<b>Wiederherzustellende Dateien und Ordner</b>"

#: data/ui/sbackup-legacy-restore.glade:345 data/ui/sbackup-restore.glade:782
msgid "Restore"
msgstr "Wiederherstellen"

#: data/ui/sbackup-legacy-restore.glade:390
msgid "Restore As..."
msgstr "Wiederherstellen als..."

#: data/ui/sbackup-legacy-restore.glade:448
msgid "Restoring, this might take some time ..."
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:463
msgid "gtk-cancel"
msgstr ""

#: data/ui/sbackup-restore.glade:38
msgid "<b>Backup destination</b>"
msgstr "<b>Sicherungsziel</b>"

#: data/ui/sbackup-restore.glade:52
msgid "Displays the manual in Help browser."
msgstr "Zeigt das Handbuch im Hilfebrowser."

#: data/ui/sbackup-restore.glade:85
msgid "Default profile's destination"
msgstr "Standardziel für Profile"

#: data/ui/sbackup-restore.glade:90
msgid ""
"Set backup destination to the place specified in default configuration "
"profile"
msgstr ""
"Den Ort der Sicherung auf den Ort einstellen, der im Standard-Profil "
"angegeben ist."

#: data/ui/sbackup-restore.glade:137
msgid "Custom destination"
msgstr "Eigenes Ziel"

#: data/ui/sbackup-restore.glade:143
msgid ""
"Select a backup destination on your harddisk or at a remote site. Press "
"Apply when ready."
msgstr ""
"Wählen Sie einen Ort für die Sicherung auf Ihrer Festplatte oder an einem "
"entfernten Ort. Klicken Sie Anwenden, wenn Sie fertig sind."

#: data/ui/sbackup-restore.glade:184
msgid "Choose a destination folder. For remote sites fill URI in text field"
msgstr ""
"Wählen Sie einen Ziel-Ordner. Für entfernte Orte tragen Sie die URI in das "
"Textfeld ein."

#: data/ui/sbackup-restore.glade:201
msgid "Change destination to path specified in left text field"
msgstr "Das Ziel in den Pfad ändern, der im linken Textfeld definiert ist"

#: data/ui/sbackup-restore.glade:266
msgid "Select a bold printed date to get the list of backups for that date."
msgstr ""
"Wählen Sie ein fett gedrucktes Datum aus, um eine Liste mit Sicherungen für "
"dieses Datum zu erhalten."

#: data/ui/sbackup-restore.glade:310
msgid "Available backups"
msgstr "Verfügbare Sicherungen"

#: data/ui/sbackup-restore.glade:398
msgid "Delete snapshot"
msgstr "Schnappschuss löschen"

#: data/ui/sbackup-restore.glade:436
msgid "Delete"
msgstr "Entfernen"

#: data/ui/sbackup-restore.glade:473
msgid "<b>Snapshot History</b>"
msgstr "<b>Verlauf der Sicherungen</b>"

#: data/ui/sbackup-restore.glade:499
msgid "Current base:"
msgstr "Derzeitige Datengrundlage:"

#: data/ui/sbackup-restore.glade:540
msgid "Select a snapshot on this list to rebase on it."
msgstr ""
"Wählen Sie aus dieser Liste eine Sicherung aus um diese als "
"Ausgangssicherung zu verwenden."

#: data/ui/sbackup-restore.glade:615
msgid "Rebase"
msgstr "Ausgangssicherung umstellen"

#: data/ui/sbackup-restore.glade:666
msgid "<b>Snapshot Management</b>"
msgstr "<b>Verwaltung von Sicherungen</b>"

#: data/ui/sbackup-restore.glade:705
msgid "Snapshot details"
msgstr "Details der Sicherung"

#: data/ui/sbackup-restore.glade:770 data/ui/sbackup-restore.glade:787
msgid "Restores files/directories from the selected snapshot"
msgstr "Wiederherstellung von Dateien/Ordner aus der ausgewählten Sicherung"

#: data/ui/sbackup-restore.glade:802 data/ui/sbackup-restore.glade:821
msgid ""
"Restores files/directories recursively starting from the base snapshot to "
"the selected snapshot"
msgstr ""
"Rekursive Wiederherstellung von Dateien/Ordner aus der ausgewählten "
"Sicherung beginnend mit der ersten Ausgangssicherung"

#: data/ui/sbackup-restore.glade:816
msgid "Revert"
msgstr "Änderungen rückgängig machen"

#: data/ui/sbackup-restore.glade:859
msgid "<b>Restoration Management</b>"
msgstr "<b>Wiederherstellung</b>"

#: data/ui/sbackup-restore.glade:884
msgid "<b>Export Management</b>"
msgstr "<b>Export-Verwaltung</b>"

#: data/ui/sbackup-restore.glade:976
msgid "Headline"
msgstr "Überschrift"

#: data/ui/sbackup-restore.glade:989
msgid "Content"
msgstr "Inhalt"

#, python-format
#~ msgid "No need to rebase a full snapshot '%s'"
#~ msgstr ""
#~ "Die Datengrundlage einer vollständigen Sicherung '%s' braucht nicht "
#~ "umgestellt werden"

#, python-format
#~ msgid ""
#~ "'%(snapshotToRebase)s'  doesn't have 'base' file , it might have been broken "
#~ msgstr ""
#~ "'%(snapshotToRebase)s' enthält keine 'base'-Datei, es ist möglicherweise "
#~ "beschädigt "

#, python-format
#~ msgid ""
#~ "Cannot rebase a snapshot on an earlier one : '%(snapshotToRebase)s' <= "
#~ "'%(NewBaseSnapshot)s' "
#~ msgstr ""
#~ "Die Datengrundlage eine Sicherung kann nicht auf eine jüngere Sicherung "
#~ "umgestellt werden: '%(snapshotToRebase)s' <= '%(NewBaseSnapshot)s' "

#, python-format
#~ msgid "Rebasing '%(current)s' on '%(base)s'"
#~ msgstr "Ändern der Basis von '%(current)s' auf '%(base)s'"

#, python-format
#~ msgid "An error occurred when pulling snapshot '%s'."
#~ msgstr "Während des Lesens der Sicherung '%s' ist ein Fehler aufgetreten."

#, python-format
#~ msgid "Base of snapshot '%s' is not set."
#~ msgstr "Ausgangssicherung des Sicherung '%s' ist nicht gesetzt."

#, python-format
#~ msgid "Cancelling pull of snapshot '%s'"
#~ msgstr "Zugriff auf Sicherung '%s' abgebrochen"

#, python-format
#~ msgid "Upgrading from v1.0 to v1.2: %s"
#~ msgstr "Umstellung von v1.0 auf v1.2: %s"

#, python-format
#~ msgid "Upgrading to v1.3: %s"
#~ msgstr "Umstellung auf v1.3: %s"

#, python-format
#~ msgid "Upgrading to v1.4: %s"
#~ msgstr "Umstellung auf v1.4: %s"

#, python-format
#~ msgid "Upgrading to v1.5: %s"
#~ msgstr "Umstellung auf v1.5: %s"

#, python-format
#~ msgid "The SNAR file already exist for snapshot '%s'. It is not overwritten."
#~ msgstr ""
#~ "Die SNAR-Datei existiert bereits für die Sicherung '%s'. Sie wird nicht "
#~ "überschrieben."

#~ msgid "The version of the snapshot is greater than the supported one!"
#~ msgstr "Die Version der Sicherung ist neuer als die unterstützten Versionen!"

#~ msgid "Unable to upgrade snapshot"
#~ msgstr "Upgrade der Sicherung konnte nicht durchgeführt werden"

#, python-format
#~ msgid "Do you really want to rebase '%(current)s' on '%(base)s' ?"
#~ msgstr ""
#~ "Möchten Sie wirklich die Basis von '%(current)s' auf '%(base)s' ändern?"

#, python-format
#~ msgid "File '%(file)s' does not exist."
#~ msgstr "Datei '%(file)s' existiert nicht."

#~ msgid "Upgrade"
#~ msgstr "Version umstellen"

#~ msgid ""
#~ "There are snapshots stored in outdated snapshot formats. Please upgrade them "
#~ "using 'Simple Backup-Restoration' if you want to use them."
#~ msgstr ""
#~ "Es gibt Sicherungen die in einem veralteten Sicherungsformat gespeichert "
#~ "wurden. Bitte diese Sicherungen mit Hilfe der Anwendung 'Simple Backup "
#~ "Wiederherstellung' upgraden um sie zu verwenden."

#, python-format
#~ msgid "Unable to remove upgrade stamp: %s"
#~ msgstr "Upgrade-Hinweis konnte nicht entfernt werden: %s"

#~ msgid ""
#~ "There are snapshots with old snapshot format. Please upgrade these using the "
#~ "Restoration tool if you want to use them."
#~ msgstr ""
#~ "Es sind snapshots in einem alten Format vorhanden. Bitte konvertieren sie "
#~ "diese mit Hilfe des Restoration Tools um sie nutzen zu können."

#, python-format
#~ msgid ""
#~ "Snapshot version is not supported (Only %(supportedversion)s is supported). "
#~ "Version '%(currentversion)s' found. You should upgrade it. "
#~ msgstr ""
#~ "Diese Version der Sicherung wird nicht unterstützt (nur Version "
#~ "%(supportedversion)s wird unterstützt). Version '%(currentversion)s' wurde "
#~ "gefunden. Sie sollten die Sicherung upgraden. "

#, python-format
#~ msgid ""
#~ "While attempting to upgrade snapshot the following error occurred:\n"
#~ "%s"
#~ msgstr ""
#~ "Beim Versuch die Sicherung zu aktualisieren trat folgender Fehler auf:\n"
#~ "%s"

#~ msgid "Do you really want to upgrade snapshot?"
#~ msgstr "Möchten Sie die Sicherung wirklich aktualisieren?"

#, python-format
#~ msgid "Upgrade snapshot '%s'"
#~ msgstr "Sicherung aktualisieren '%s'"

#~ msgid "Snapshot was sucessfully upgraded."
#~ msgstr "Sicherung wurde erfolgreich aktualisiert."

#~ msgid "Upgrade finished"
#~ msgstr "Upgrade beendet"

#~ msgid "Simple Backup upgrade"
#~ msgstr "Einfache Aktualisierung der Sicherungsdatei"

#, python-format
#~ msgid ""
#~ "Upgrading the selected snapshot `%s` might corrupt your backup for this "
#~ "particular point in time. You cannot undo this operation. It is recommended "
#~ "to create a copy of the snapshot directory before upgrading it. The upgrade "
#~ "process takes a while - be patient.\n"
#~ "\n"
#~ "Are you sure that you want to upgrade the snapshot now?"
#~ msgstr ""
#~ "Wenn Sie die gewählte Sicherungsdatei '%s' aktualisieren, kann das Ihre "
#~ "Sicherung für diesen Zeitpunkt zerstören. Sie können die Aktion nicht "
#~ "rückgängig machen. Es wird empfohlen, dass Sie eine Kopie der "
#~ "Sicherungsdatei erstellen, bevor Sie sie aktualisieren. Der "
#~ "Aktualisierungsprozess dauert eine Weile, haben Sie einen Augenblick "
#~ "Geduld.\n"
#~ "\n"
#~ "Sind Sie sicher, dass Sie die Sicherungsdatei jetzt aktualisieren möchten?"

#~ msgid "Upgrade snapshot"
#~ msgstr "Sicherungsdatei aktualisieren"
