# Italian translation for sbackup
# Copyright (c) 2006 Rosetta Contributors and Canonical Ltd 2006
# This file is distributed under the same license as the sbackup package.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2006.
#
msgid ""
msgstr ""
"Project-Id-Version: sbackup\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2013-01-10 22:47+0100\n"
"PO-Revision-Date: 2011-02-06 11:43+0000\n"
"Last-Translator: Jean-Peer Lorenz <Unknown>\n"
"Language-Team: Italian <it@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Launchpad-Export-Date: 2013-01-11 04:47+0000\n"
"X-Generator: Launchpad (build 16412)\n"

#: src/sbackup/backupproc.py:169 src/sbackup/pkginfo.py:85
#, python-format
msgid "SBackup Daemon <%(login)s@%(hostname)s>"
msgstr "Demone SBackup <%(login)s@%(hostname)s>"

#: src/sbackup/backupproc.py:173
#, python-format
msgid "[SBackup] [%(profile)s] Report of %(date)s"
msgstr "[SBackup] [%(profile)s] Rapporto del %(date)s"

#: src/sbackup/backupproc.py:178 src/sbackup/core/profile_handler.py:282
msgid "No log file specified."
msgstr "Nessun file di registro specificato."

#: src/sbackup/backupproc.py:183
msgid "Unable to find log file."
msgstr "Impossibile trovare il file di registro."

#: src/sbackup/backupproc.py:251
msgid ""
"Critical Error: No configuration file for the default profile was found!\n"
"\n"
"Now continue processing remaining profiles."
msgstr ""
"Errore critico: non è stato trovato alcun file di configurazione per il "
"profilo predefinito.\n"
"\n"
"Continuare elaborando i profili rimanenti."

#: src/sbackup/backupproc.py:302
msgid "Backup was canceled by user."
msgstr "Backup annullato dall'utente."

#: src/sbackup/backupproc.py:307
msgid "An error occurred during the cancellation of backup:"
msgstr "Si è verificato un errore durante l'annullamento del backup:"

#: src/sbackup/backupproc.py:313
msgid "An error occurred during the backup:"
msgstr "Si è verificato un errore durante il backup:"

#: src/sbackup/backupproc.py:330
msgid "Error when sending email:"
msgstr "Errore durante l'invio dell'email:"

#: src/sbackup/backupproc.py:361
msgid "The following error(s) occurred before:"
msgstr "Si sono verificati i seguenti errori:"

#: src/sbackup/backupproc.py:532
#, python-format
msgid ""
"Backup is not being started.\n"
"%s"
msgstr ""
"Il backup non è stato avviato.\n"
"%s"

#: src/sbackup/pkginfo.py:42
msgid ""
"This is a user friendly backup solution for common desktop needs. If you "
"want to help by submitting bugs, by translating or anything else please "
"visit our website."
msgstr ""
"Questa è una soluzione di backup di facile utilizzo per le esigenze dei "
"comuni desktop. Per contribuire segnalando bug, traducendo o facendo "
"qualunque altra cosa visitare il sito web del progetto."

#: src/sbackup/pkginfo.py:45
msgid "Maintainers:"
msgstr "Manutentori:"

#: src/sbackup/pkginfo.py:49
msgid "Former maintainers:"
msgstr "Precedenti manutentori:"

#: src/sbackup/pkginfo.py:53
msgid "Contributors:"
msgstr "Contributori:"

#: src/sbackup/pkginfo.py:70
msgid "translator-credits"
msgstr ""
"Ubuntu Italian Translators, https://launchpad.net/~ubuntu-l10n-it, 2006-"
"2007\n"
"\n"
"Launchpad Contributions:\n"
"  Alessio Treglia https://launchpad.net/~quadrispro\n"
"  Claudio Arseni https://launchpad.net/~claudio.arseni\n"
"  Jean-Peer Lorenz https://launchpad.net/~peer.loz\n"
"  LoReNicolò https://launchpad.net/~god121-p-l\n"
"  Luca Ferretti https://launchpad.net/~elle.uca\n"
"  Lucius https://launchpad.net/~lucius-ald\n"
"  Michele Angrisano https://launchpad.net/~darksun88-deactivatedaccount\n"
"  Milo Casagrande https://launchpad.net/~milo\n"
"  Riccardo Angelino https://launchpad.net/~riccardoangelino\n"
"  enubuntu https://launchpad.net/~enubuntu\n"
"  frazar0 https://launchpad.net/~frazar0\n"
"  katane https://launchpad.net/~skorpio1066"

#: src/sbackup/ar_backend/tar.py:109 src/sbackup/ar_backend/tar.py:167
#: src/sbackup/ar_backend/tar.py:213
msgid "Invalid archive type."
msgstr "Tipo di archivio non valido."

#: src/sbackup/ar_backend/tar.py:123
#, python-format
msgid "Effective path for `%s` is not available"
msgstr "Il percorso effettivo per \"%s\" non è disponibile"

#: src/sbackup/ar_backend/tar.py:295
#, python-format
msgid "Unable to get effective path for `%s`"
msgstr "Impossibile ottenere il percorso effettivo per \"%s\""

#: src/sbackup/ar_backend/tar.py:344
msgid ""
"For the moment split functionality is not compatible with compress option."
msgstr ""
"Al momento la funzione di divisione non è compatibile con l'opzione di "
"compressione."

#: src/sbackup/ar_backend/tar.py:353 src/sbackup/ar_backend/tar.py:414
#: src/sbackup/core/profile_handler.py:292
#, python-format
msgid "Unable to change permissions for file '%s'."
msgstr "Impossibile cambiare i permessi per il file \"%s\"."

#: src/sbackup/ar_backend/tar.py:362
#, python-format
msgid "Unable to remove temporary file `%(file)s`: %(error)s"
msgstr "Impossibile rimuovere il file temporaneo \"%(file)s\": %(error)s"

#: src/sbackup/ar_backend/tar.py:378
msgid "Launching TAR to make incremental backup."
msgstr "Avvio di TAR per eseguire backup incrementale."

#: src/sbackup/ar_backend/tar.py:407
msgid "Unable to find the SNAR file to make an incremental backup."
msgstr ""
"Impossibile trovare il file SNAR per eseguire un backup incrementale."

#: src/sbackup/ar_backend/tar.py:408
msgid "Falling back to full backup."
msgstr "Ripiegare sul backup completo."

#: src/sbackup/ar_backend/tar.py:450
msgid "Launching TAR to make a full backup."
msgstr "Avvio di TAR per eseguire backup completo."

#: src/sbackup/ar_backend/tar.py:517
msgid "Leading '/' from member names were removed."
msgstr "La \"/\" principale è stata rimossa dai nomi dei membri."

#: src/sbackup/ar_backend/tar.py:519
msgid "Leading '/' from hard link targets were removed."
msgstr "La \"/\" principale è stata rimossa dai collegamenti hard link"

#: src/sbackup/ar_backend/tar.py:528
#, python-format
msgid "TAR returned a message: %s"
msgstr "TAR ha restituito un messaggio: %s"

#: src/sbackup/ar_backend/tar.py:530
#, python-format
msgid ""
"TAR returned messages:\n"
"%s"
msgstr ""
"TAR ha restituito dei messaggi:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:533
msgid "TAR has been finished successfully."
msgstr "TAR è stato completato con successo."

#: src/sbackup/ar_backend/tar.py:537
#, python-format
msgid "TAR returned a warning: %s"
msgstr "TAR ha restituito un avviso: %s"

#: src/sbackup/ar_backend/tar.py:539
#, python-format
msgid ""
"TAR returned warnings:\n"
"%s"
msgstr ""
"TAR ha restituito avvisi:\n"
"%s"

#: src/sbackup/ar_backend/tar.py:542
msgid "TAR returned warnings but has been finished successfully."
msgstr "TAR ha restituito degli avvisi ma e' stato completato con successo."

#: src/sbackup/ar_backend/tar.py:546
msgid "Unable to finish successfully. TAR terminated with errors."
msgstr ""
"Impossibile completare con successo. TAR è stato terminato con errori."

#: src/sbackup/ar_backend/tar.py:727
#, python-format
msgid "Unable to terminate backend process: %s"
msgstr "Impossibile terminare il processo in backend: %s"

#: src/sbackup/ar_backend/tar.py:760
msgid "Included"
msgstr "Incluso"

#: src/sbackup/ar_backend/tar.py:760
msgid "Not changed"
msgstr "Invariato"

#: src/sbackup/ar_backend/tar.py:760
msgid "Directory"
msgstr "Directory"

#: src/sbackup/ar_backend/tar.py:788
msgid "Line must be a string"
msgstr "La riga deve essere una stringa"

#: src/sbackup/ar_backend/tar.py:804
msgid "Dumpdir inconsistancy : 'filename' is empty"
msgstr "Directory di dump inconsistente: «filename» è vuoto"

#: src/sbackup/ar_backend/tar.py:817
msgid "Dumpdir inconsistancy : 'control' is empty"
msgstr "Directory di dump inconsistente: «control» è vuoto"

#: src/sbackup/ar_backend/tar.py:890
#, python-format
msgid "File '%s' does not exist."
msgstr "Il file «%s» non esiste."

#: src/sbackup/ar_backend/tar.py:1020 src/sbackup/ar_backend/tar.py:1054
#: src/sbackup/ar_backend/tar.py:1154
msgid "The snarfile header is incomplete."
msgstr "Intestazione del file snar incompleta."

#: src/sbackup/ar_backend/tar.py:1323
msgid "A SnapshotFile is required"
msgstr "È richiesto un file immagine"

#: src/sbackup/ar_backend/tar.py:1423
#, python-format
msgid "Directory does not exist: %s."
msgstr "La directory non esiste: %s."

#: src/sbackup/core/ConfigManager.py:330
#, python-format
msgid "Profile settings are being read from file '%s'."
msgstr "Le impostazioni del profilo vengono lette dal file «%s»."

#: src/sbackup/core/ConfigManager.py:333
#, python-format
msgid ""
"Profile settings are being set to default values. Configuration file is set "
"to '%s'."
msgstr ""
"Le impostazioni di profilo sono regolate ai valori di default. Il file di "
"configurazione è impostato a '%s'."

#: src/sbackup/core/ConfigManager.py:479
msgid "Option 'target' is missing, aborting."
msgstr "Opzione «target» mancante, chiusura in corso."

#: src/sbackup/core/ConfigManager.py:547
#, python-format
msgid ""
"Error while processing configuration:\n"
"\n"
"%(error)s in line `%(line)s`.\n"
"\n"
"Please check your configuration file."
msgstr ""
"Errore durante nell'elaborazione della configurazione:\n"
"\n"
"%(error)s alla linea `%(line)s`.\n"
"\n"
"Si prega di controllare il file di configurazione."

#: src/sbackup/core/ConfigManager.py:588 src/sbackup/core/ConfigManager.py:622
#, python-format
msgid ""
"Unable to evaluate '%(parameter)s' as a dictionary (value got = '%(value)r')."
msgstr ""
"Impossibile considerare «%(parameter)s» come un dizionario (valore ottenuto "
"= «%(value)r»)."

#: src/sbackup/core/ConfigManager.py:614
#, python-format
msgid ""
"Couldn't evaluate '%(parameter)s' as a dictionary (value got = '%(value)r' )"
msgstr ""
"Impossibile considerare «%(parameter)s» come un dizionario (valore ottenuto "
"= «%(value)r»)"

#: src/sbackup/core/ConfigManager.py:638
msgid "You must provide a dictionary."
msgstr "È necessario fornire un dizionario."

#: src/sbackup/core/ConfigManager.py:755
#, python-format
msgid "Log output for [%(profile)s] is directed to file '%(file)s'."
msgstr "Output del registro di [%(profile)s] inviato al file «%(file)s»."

#: src/sbackup/core/ConfigManager.py:762
#, python-format
msgid "Log output for [%s] is not directed into a file."
msgstr "Output del registro di [%s] non inviato a nessun file."

#: src/sbackup/core/ConfigManager.py:781
#, python-format
msgid "Unable to rename log file '%(src)s'->'%(dst)s': %(err)s"
msgstr ""
"Impossibile rinominare il file di registro «%(src)s»->«%(dst)s»: %(err)s"

#: src/sbackup/core/ConfigManager.py:801
#, python-format
msgid "The config file '%s' couldn't be read!"
msgstr "Il file di configurazione '%s' non può essere letto!"

#: src/sbackup/core/ConfigManager.py:813
#, python-format
msgid "section [%(section)s] in '%(configfile)s' should not exist, aborting"
msgstr ""
"sezione [%(section)s] in «%(configfile)s» inesistente, chiusura in corso"

#: src/sbackup/core/ConfigManager.py:895
msgid "No schedule defined in configuration file. Probing from filesystem."
msgstr ""
"Nessuna pianificazione definita nel file di configurazione. Interrogazione "
"del filesystem."

#: src/sbackup/core/ConfigManager.py:988
#: src/sbackup/core/ConfigManager.py:1000
msgid "The config file is not set yet into this ConfigManager"
msgstr ""
"Il file di configurazione non è ancora impostato in questo ConfigManager"

#: src/sbackup/core/ConfigManager.py:1163
msgid "No receiver set."
msgstr "Nessun destinatario impostato."

#: src/sbackup/core/ConfigManager.py:1165
msgid "No SMTP server set."
msgstr "Nessun server SMTP impostato."

#: src/sbackup/core/ConfigManager.py:1168
msgid "Username set but no password specified."
msgstr "Nome utente impostato ma nessuna password specificata."

#: src/sbackup/core/ConfigManager.py:1171
msgid "Password set but no username specified."
msgstr "Password impostata ma nome utente non specificato."

#: src/sbackup/core/ConfigManager.py:1174
msgid ""
"A certificate and key file is given while SSL option (smtptls=1) is not "
"set.\n"
"Select SSL in order to use Certificate and Key."
msgstr ""
"Un certificato e una chiave sono stati forniti mentre l'opzione SSL "
"(smtptls=1) non è stata impostata.\n"
"Selezionare SSL per poter utilizzare certificato e chiave."

#: src/sbackup/core/ConfigManager.py:1178
msgid ""
"When specifying a SSL certificate or key file, a key file resp. certificate "
"is mandatory."
msgstr ""
"Quando si imposta un certificato SSL o una chiave è obbligatorio inserire il "
"certificato."

#: src/sbackup/core/ConfigManager.py:1373
msgid "Default Profile"
msgstr "Profilo predefinito"

#: src/sbackup/core/ConfigManager.py:1374
msgid "Unknown Profile"
msgstr "Profilo sconosciuto"

#: src/sbackup/core/ConfigManager.py:1428
msgid "Unlimited"
msgstr "Illimitato"

#: src/sbackup/core/ConfigManager.py:1429
msgid "100 MiB"
msgstr "100 MiB"

#: src/sbackup/core/ConfigManager.py:1430
msgid "250 MiB"
msgstr "250 MiB"

#: src/sbackup/core/ConfigManager.py:1431
msgid "650 MiB"
msgstr "650 MiB"

#: src/sbackup/core/ConfigManager.py:1432
msgid "2 GiB (FAT16)"
msgstr "2 GiB (FAT16)"

#: src/sbackup/core/ConfigManager.py:1433
msgid "4 GiB (FAT32)"
msgstr "4 GiB (FAT32)"

#: src/sbackup/core/ConfigManager.py:1434 src/sbackup/ui/configgui.py:279
#: src/sbackup/ui/configgui.py:1418
msgid "Custom"
msgstr "Personalizzato"

#: src/sbackup/core/ConfigManager.py:1436
msgid "MP3 Music"
msgstr "Musica MP3"

#: src/sbackup/core/ConfigManager.py:1437
msgid "AVI Video"
msgstr "Video AVI"

#: src/sbackup/core/ConfigManager.py:1438
#: src/sbackup/core/ConfigManager.py:1439
msgid "MPEG Video"
msgstr "Video MPEG"

#: src/sbackup/core/ConfigManager.py:1440
msgid "Matrjoshka Video"
msgstr "Video Matrjoshka"

#: src/sbackup/core/ConfigManager.py:1441
msgid "OGG Multimedia container"
msgstr "Contenitore multimediale OGG"

#: src/sbackup/core/ConfigManager.py:1442
msgid "CD Images"
msgstr "Immagini CD"

#: src/sbackup/core/RestoreManager.py:80
#, python-format
msgid "File '%s' not found in the backup snapshot files list"
msgstr ""
"Il file «%s» non è stato trovato nell'elenco dei file dell'immagine di backup"

#: src/sbackup/core/RestoreManager.py:82
#, python-format
msgid ""
"File '%(filename)s' not found in snapshot's [%(snapshotname)s] files list, "
"Skipped."
msgstr ""
"File '%(filename)s' non trovati nella lista file immagine "
"[%(snapshotname)s], Saltato."

#: src/sbackup/core/SnapshotManager.py:114
#, python-format
msgid "Snapshot '%s' not found "
msgstr "Immagine «%s» non trovata "

#: src/sbackup/core/SnapshotManager.py:210
#, python-format
msgid "Invalid snapshot `%(name)s` found: Name of snapshot not valid."
msgstr ""
"Immagine non valido `%(name)s` non trovato: Nome dell' immagine non valido."

#: src/sbackup/core/SnapshotManager.py:213
#, python-format
msgid "Invalid snapshot `%(name)s` found: %(error_cause)s."
msgstr "Immagine non valido `%(name)s` non trovato: %(error_cause)s."

#: src/sbackup/core/SnapshotManager.py:286
msgid "The snarfile header is incomplete !"
msgstr "L'intestazione del file snar è incompleta."

#: src/sbackup/core/SnapshotManager.py:429
#, python-format
msgid ""
"Snapshot '%s' is already Full, nothing to do (not changing it to full)."
msgstr ""
"Immagine «%s» già completa, nulla da fare (non viene modificata in completa)."

#: src/sbackup/core/profile_handler.py:101
#, python-format
msgid "Running of hooks: %s"
msgstr ""

#: src/sbackup/core/profile_handler.py:111
msgid "Preparation of backup process"
msgstr "Preparazione del processo di backup"

#: src/sbackup/core/profile_handler.py:146
#, python-format
msgid "Snapshot '%(name)s' is being made."
msgstr "Immagine «%(name)s» creata."

#: src/sbackup/core/profile_handler.py:154
#, python-format
msgid "Setting Base to '%(value)s'."
msgstr "Base impostata a «%(value)s»."

#: src/sbackup/core/profile_handler.py:163
msgid "Setting packages File."
msgstr "File dei pacchetti impostato."

#: src/sbackup/core/profile_handler.py:169
msgid "Problem when setting the packages list: "
msgstr "Problemi durante l'impostazione dell'elenco pacchetti: "

#: src/sbackup/core/profile_handler.py:173
msgid "Setting Excludes File."
msgstr "Impostazione file esclusi."

#: src/sbackup/core/profile_handler.py:181
#, python-format
msgid "Setting compression format to `%s`"
msgstr "Impostare il formato di compressione a `%s`"

#: src/sbackup/core/profile_handler.py:188
#, python-format
msgid "Setting size of archive chunks to %s"
msgstr "Impostazione delle dimensioni dei pezzi di repertorio %s"

#: src/sbackup/core/profile_handler.py:195
msgid "Option 'Follow symbolic links' is enabled."
msgstr "L'opzione «Segui collegamenti simbolici» è abilitata."

#: src/sbackup/core/profile_handler.py:197
msgid "Option 'Follow symbolic links' is disabled."
msgstr "L'opzione «Segui collegamenti simbolici» è disabilitata."

#: src/sbackup/core/profile_handler.py:206
msgid "Snapshot is being committed"
msgstr "Lo snapshot è stato invitato."

#: src/sbackup/core/profile_handler.py:220
#, python-format
msgid "Error while purging old snapshots: %s"
msgstr "Si sono verificati degli errori cancellando vecchi snapshots: %s"

#: src/sbackup/core/profile_handler.py:222
msgid "Backup process finished."
msgstr "Backup completato."

#: src/sbackup/core/profile_handler.py:229
msgid "Inspect file system and collect file infos"
msgstr ""
"Sto inspezionando il file system per collezionare le informazioni sui files"

#: src/sbackup/core/profile_handler.py:240
msgid "Summary of backup"
msgstr "Riepilogo di backup"

#: src/sbackup/core/profile_handler.py:241
#, python-format
msgid "Number of directories: %s."
msgstr "Numero di directory: %s."

#: src/sbackup/core/profile_handler.py:242
#, python-format
msgid "Total number of files: %s."
msgstr "Numero totale di file: %s."

#: src/sbackup/core/profile_handler.py:243
#, python-format
msgid "Number of symlinks: %s."
msgstr "Numero di collegamenti simbolici: %s."

#: src/sbackup/core/profile_handler.py:244
#, python-format
msgid "Number of files included in snapshot: %s."
msgstr "Numero di file inclusi nell'immagine: %s."

#: src/sbackup/core/profile_handler.py:245
#, python-format
msgid "Number of new files (also included): %s."
msgstr ""

#: src/sbackup/core/profile_handler.py:246
#, python-format
msgid "Number of files skipped in incremental snapshot: %s."
msgstr "Numero di file saltati nell'immagine incrementale: %s."

#: src/sbackup/core/profile_handler.py:247
#, python-format
msgid "Number of items forced to be excluded: %s."
msgstr "Numero di elementi forzati ad essere esclusi: %s"

#: src/sbackup/core/profile_handler.py:248
#, python-format
msgid "Number of items to be excluded by config: %s."
msgstr "Numero di oggetti da escludere come da configurazione: %s"

#: src/sbackup/core/profile_handler.py:249
#, python-format
msgid "Maximum free size required is '%s'."
msgstr "Lo spazio libero massimo richiesto è '%s'"

#: src/sbackup/core/profile_handler.py:255
#, python-format
msgid "Available disk size is '%s'."
msgstr "La dimensione dello spazio disponibile su disco è '%s'"

#: src/sbackup/core/profile_handler.py:257
#, python-format
msgid ""
"Not enough free space in the target directory for the planned backup (free: "
"%(freespace)s, required: %(neededspace)s)."
msgstr ""
"Spazio disponibile non sufficiente nella directory per il backup pianificato "
"(libero: %(freespace)s, richiesto: %(neededspace)s)."

#: src/sbackup/core/profile_handler.py:277
msgid "Unable to copy log. File access is not initialized."
msgstr ""
"Impossibile copiare il registro. L'accesso al file non è inizializzato."

#: src/sbackup/core/profile_handler.py:295
#, python-format
msgid "Unable to copy log file: %s"
msgstr "Impossibile copiare il file di registro: %s"

#: src/sbackup/core/profile_handler.py:297
msgid "Unable to find logfile to copy into snapshot."
msgstr "Impossibile trovare il logfile da copiare in snapshot."

#: src/sbackup/core/profile_handler.py:299
msgid "No snapshot to copy logfile."
msgstr "Nessuna immagine per copiare il file di registro"

#: src/sbackup/core/profile_handler.py:306
msgid "Processing of profile was canceled on user request\n"
msgstr ""
"Elaborazione del profilo è stata annullata su richiesta dell'utente\n"

#: src/sbackup/core/profile_handler.py:323
msgid "Processing of profile successfully finished (no errors)\n"
msgstr "Elaborazione del profilo terminato con successo (nessun errore)\n"

#: src/sbackup/core/profile_handler.py:329
#, python-format
msgid "Processing of profile failed with error: %s\n"
msgstr "Elaborazione del profile non riuscita con errore: %s\n"

#: src/sbackup/core/profile_handler.py:340
#, python-format
msgid "Backup destination: %s"
msgstr "Destinazione del backup: %s"

#: src/sbackup/core/profile_handler.py:344
msgid "Unable to find destination directory."
msgstr "Impossibile trovare la directory di destinazione."

#: src/sbackup/core/profile_handler.py:363
msgid "Unable to find destination directory even after retry."
msgstr ""
"Impossibile trovare la directory di destinazione anche dopo il nuovo "
"tentativo."

#: src/sbackup/core/profile_handler.py:364
#: src/sbackup/core/profile_handler.py:371
#, python-format
msgid "Target directory '%(target)s' does not exist."
msgstr "La directory di destinazione «%(target)s» non esiste."

#: src/sbackup/core/profile_handler.py:377
#, python-format
msgid "Unable to access destination: %s"
msgstr "Impossibile accedere alla destinazione: %s"

#: src/sbackup/core/snapshot.py:134
msgid "Snapshot is inconsistent: __name is not set "
msgstr "L'immagine è inconsistente: _name non impostato "

#: src/sbackup/core/snapshot.py:145
#, python-format
msgid "Name of snapshot '%s' doesn't match requirement"
msgstr "Il nome dell'immagine «%s» non corrisponde ai requisiti"

#: src/sbackup/core/snapshot.py:239
msgid "Snapshot is inconsistent: __snapshotpath is not set "
msgstr "L'immagine è inconsistente: __snapshotpath non impostato "

#: src/sbackup/core/snapshot.py:318
#, python-format
msgid ""
"The snapshot compression format is supposed to be '%s' but the corresponding "
"well named file wasn't found"
msgstr ""
"Il formato di compressione delle immagini dovrebbe essere «%s», ma il file "
"corrispondente non è stato trovato"

#: src/sbackup/core/snapshot.py:342
#, python-format
msgid ""
"%(file)s doesn't contain valid value. Ignoring incomplete or non - backup "
"directory. "
msgstr ""
"%(file)s non contiene valori validi. Ignorata directory incompleta o non di "
"backup. "

#: src/sbackup/core/snapshot.py:478
#, python-format
msgid "Name of Snapshot not valid : %s"
msgstr "Nome dell'immagine non valido: %s"

#: src/sbackup/core/snapshot.py:496
#, python-format
msgid "Name of base not valid : %s"
msgstr "Nome della base non valido: %s"

#: src/sbackup/core/snapshot.py:542
#, python-format
msgid "Invalid name of snapshot: %s"
msgstr "Nome dell'immagine non valido: %s"

#: src/sbackup/core/snapshot.py:546
msgid "Unable to read mandatory file `ver`"
msgstr "Impossibile leggere il file obbligatorio \"ver\""

#: src/sbackup/core/snapshot.py:591
msgid "Base name must be set for incremental backup."
msgstr "Il nome di base deve essere impostato per il backup incrementale."

#: src/sbackup/fs_backend/_fuse_fam.py:106
msgid "Initializing FUSE File Access Manager."
msgstr "Inizializzazione del gestore di accesso ai file FUSE."

#: src/sbackup/fs_backend/_fuse_fam.py:129
msgid "Terminating FUSE File Access Manager."
msgstr "Chiusura del gestore di accesso ai file FUSE."

#: src/sbackup/fs_backend/_fuse_utils.py:45
#: src/sbackup/fs_backend/_gio_utils.py:109
msgid "SFTP"
msgstr "SFTP"

#: src/sbackup/fs_backend/_fuse_utils.py:46
#: src/sbackup/fs_backend/_gio_utils.py:110
msgid "SSH"
msgstr "SSH"

#: src/sbackup/fs_backend/_fuse_utils.py:47
#: src/sbackup/fs_backend/_gio_utils.py:111
msgid "FTP"
msgstr "FTP"

#: src/sbackup/fs_backend/_gio_fam.py:100
msgid "Initializing GIO File Access Manager."
msgstr "Inizializzazione del gestore di accesso ai file GIO."

#: src/sbackup/fs_backend/_gio_fam.py:114
msgid "Terminating GIO File Access Manager."
msgstr "Chiusura del gestore di accesso ai file GIO."

#: src/sbackup/fs_backend/_gio_utils.py:95
msgid "Unknown error code:"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:112
msgid "NFS"
msgstr "NFS"

#: src/sbackup/fs_backend/_gio_utils.py:113
msgid "SMB"
msgstr "SMB"

#: src/sbackup/fs_backend/_gio_utils.py:193
msgid "Unable to get mount: path is not mounted"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:195
msgid "Unable to get mount: path not found when mounting (is probably local)"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:197
#: src/sbackup/fs_backend/_gio_utils.py:200
#, python-format
msgid "Unable to get mount: %s"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:250
msgid "Unable to un-set mount flag: path is not stored"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:352
msgid "Path is already mounted."
msgstr "Il percorso è già montato."

#: src/sbackup/fs_backend/_gio_utils.py:380
msgid "Path is not mounted."
msgstr "Il percorso non è montato."

#: src/sbackup/fs_backend/_gio_utils.py:887
msgid "test specified path for existence using GIO"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:900
msgid "Create testdir"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:905
msgid "Test testfile for existence"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:912
msgid "Create file"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:919
msgid "Re-read test file"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:931
msgid "Remove file"
msgstr ""

#: src/sbackup/fs_backend/_gio_utils.py:933
msgid "Remove dir"
msgstr ""

#: src/sbackup/fuse_plugins/__init__.py:160
#, python-format
msgid "Unable to import plugin `%(plugin_name)s`: %(error_cause)s "
msgstr ""
"Impossibile importare il plugin \"%(plugin_name)s\": %(error_cause)s "

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:117
#, python-format
msgid ""
"Couldn't found external application 'curlftpfs' needed for handling of ftp "
"sites: %s"
msgstr ""
"Impossibile trovare l'applicazione esterna «curlftpfs» necessaria per "
"l'utilizzo di siti ftp: %s"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:127
#: src/sbackup/fuse_plugins/sftpFuseFAM.py:124
#, python-format
msgid "Couldn't mount '%(server)s' into '%(mountpoint)s' : %(error)s"
msgstr "Impossibile montare «%(server)s» in «%(mountpoint)s»: %(error)s"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:141
msgid "FTP schema is: ftp://user:pass@server/anything"
msgstr "Lo schema FTP è: ftp://utente:password@server/qualcosa"

#: src/sbackup/fuse_plugins/ftpFuseFAM.py:188
#, python-format
msgid ""
"Error matching the schema 'ftp://user:pass@server/anything' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Errore di corrispondenza tra «ftp://utente:password@server/cartella» e «%s» "
"(la «/» dopo server è obbligatoria)"

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:114
#, python-format
msgid ""
"Couldn't found external application 'curlftpfs' needed for handling of sftp "
"sites: %s"
msgstr ""

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:138
msgid "SFTP schema is like : sftp://user:pass@server/anything"
msgstr "Un indirizzo SFTP è simile a: sftp://utente:password@server/cartella"

#: src/sbackup/fuse_plugins/sftpFuseFAM.py:185
#, python-format
msgid ""
"Error matching the schema 'sftp://user:pass@server/anything' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Errore di corrispondenza tra «sftp://utente:password@server/cartella» e «%s» "
"(la «/» dopo server è obbligatoria)"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:81
#, python-format
msgid ""
"Error matching the schema 'ssh://user:pass@example.com/home/' with '%s' (The "
"'/' after server is mandatory)"
msgstr ""
"Errore di corrispondenza tra «ssh://utente:password@esempio.it/home/» e «%s» "
"(la «/» dopo server è obbligatoria)"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:137
#, python-format
msgid ""
"The sshfs command '%(command)s' didn't perform normally. Output => "
"%(erroroutput)s "
msgstr ""
"Il comando sshfd '%(command)s' non viene eseguito normalmente. Output => "
"%(erroroutput)s "

#: src/sbackup/fuse_plugins/sshFuseFAM.py:142
msgid "SSH schema is like : ssh://user:pass@example.com:33/home/user/backup/"
msgstr ""
"Lo schema SSH è simile a  : ssh://user:pass@example.com:33/home/user/backup"

#: src/sbackup/fuse_plugins/sshFuseFAM.py:158
#, python-format
msgid ""
"Error matching the schema 'ssh://user:pass@example.com:21/home/' with '%s' "
"(The '/' after server is mandatory)"
msgstr ""
"Errore nella corrispondenza dello schema "
"'ssh://user:pass@example.com:21/home' con '%s' (Lo '/' dopo il server è "
"obbligatorio)"

#: src/sbackup/ui/GladeWindow.py:210
msgid ""
"Please make sure the missing directory exists (e.g. by mounting an external "
"disk) or change the specified target."
msgstr ""

#: src/sbackup/ui/GladeWindow.py:211
#, python-format
msgid ""
"While accessing the backup destination following error occurred:\n"
"\n"
"%s."
msgstr ""

#: src/sbackup/ui/GladeWindow.py:212 src/sbackup/ui/restoregui.py:797
msgid "Simple Backup error"
msgstr "Errore di Simple Backup"

#: src/sbackup/ui/GladeWindow.py:213
msgid "Unable to access backup destination"
msgstr ""

#: src/sbackup/ui/configgui.py:125
msgid "Scheduled backups are available for Administrator users only."
msgstr "I backup programmati sono disponibili solo per gli amministratori."

#: src/sbackup/ui/configgui.py:135 src/sbackup/ui/configgui.py:144
msgid "Name"
msgstr "Nome"

#: src/sbackup/ui/configgui.py:152
msgid "File Type"
msgstr "Tipo di file"

#: src/sbackup/ui/configgui.py:187
msgid "Enable"
msgstr "Abilita"

#: src/sbackup/ui/configgui.py:188
msgid "Profile Name"
msgstr "Nome del profilo"

#: src/sbackup/ui/configgui.py:285
#, python-format
msgid ""
"Invalid or empty regular expression ('%s') found in configuration. Removed."
msgstr ""
"Espressione regolare (\"%s\")  vuota o non valida trovata nella "
"configurazione. Rimossa."

#: src/sbackup/ui/configgui.py:292
#, python-format
msgid ""
"Invalid or empty regular expressions found\n"
"in configuration file:\n"
"'%s'\n"
"\n"
"These expressions are not used and were\n"
"removed from the configuration."
msgstr ""
"Espressioni regolari vuote o non valide trovate\n"
"nel file di configurazione:\n"
"\"%s\"\n"
"\n"
"Queste espressioni non sono state usate e sono\n"
"state rimosse dalla configurazione."

#: src/sbackup/ui/configgui.py:548
msgid ""
"Please make sure the missing directory exists (e.g. by mounting an external "
"disk) or change the specified target to an existing one."
msgstr ""
"Assicurarsi che la directory mancante esista (es. montando un disco esterno) "
"o cambiare la destinazione con una esistente."

#: src/sbackup/ui/configgui.py:549
#, python-format
msgid ""
"Backup target `%s` does not exist.\n"
"\n"
"Attention: The target will be set to the default value. Check this on the "
"destination settings page before saving the configuration."
msgstr ""
"La destinazione del backup \"%s\" non esiste.\n"
"\n"
"Attenzione: la destinazione dovrà essere impostata al valore predefinito. "
"Controllare questi parametri nella pagina delle impostazioni della "
"destinazione prima di salvare la configurazione."

#: src/sbackup/ui/configgui.py:551
msgid "Unable to open backup target"
msgstr "Impossibile aprire l'oggetto di backup"

#: src/sbackup/ui/configgui.py:623
#, python-format
msgid ""
"%s\n"
"\n"
"A backup profile using default values was created. Save the new "
"configuration in order to use it or check your existing configuration file "
"manually.\n"
"\n"
"Important note: Saving will overwrite your existing invalid configuration."
msgstr ""
"%s\n"
"\n"
"È stato creato un profilo di backup usando i valori predefiniti. Salvare la "
"nuova configurazione per utilizzarla o controllare manualmente il file di "
"configurazione esistente.\n"
"\n"
"Nota importante: il salvataggio sovrascriverà la configurazione non valida "
"esistente."

#: src/sbackup/ui/configgui.py:641
#, python-format
msgid "Current profile: %s"
msgstr "Profilo attuale: %s"

#: src/sbackup/ui/configgui.py:732
msgid "Already included item !"
msgstr "Oggetto già incluso."

#: src/sbackup/ui/configgui.py:747
msgid "Already excluded item !"
msgstr "Oggetto già escluso."

#: src/sbackup/ui/configgui.py:759 src/sbackup/ui/configgui.py:1458
msgid "Empty expression. Please enter a valid regular expression."
msgstr "Espressione vuota. Inserire un'espressione regolare valida."

#: src/sbackup/ui/configgui.py:774 src/sbackup/ui/configgui.py:1472
msgid "Provided regular expression is not valid."
msgstr "L'espressione regolare fornita non è valida."

#: src/sbackup/ui/configgui.py:782
msgid "Empty filename or path. Please enter a valid filename or path."
msgstr ""
"Nome file o per percorso vuoto. Inserire un nome file o un percorso valido."

#: src/sbackup/ui/configgui.py:791
msgid ""
"It seems the path you entered does not exists. Do you want to add this "
"incorrect path?"
msgstr ""
"Sembra che il percorso selezionato non esista. Aggiungere questo percorso "
"non corretto?"

#: src/sbackup/ui/configgui.py:820
msgid "Save configuration as..."
msgstr "Salva la configurazione come..."

#: src/sbackup/ui/configgui.py:887
msgid ""
"A backup process is now executed in the background.\n"
"\n"
"You can monitor the progress of the backup by means of the status indicator "
"displayed in the notification area."
msgstr ""
"Un processo di backup è ora eseguito in background.\n"
"\n"
"È possibile controllarne l'avanzamento utilizzando l'indicatore di stato "
"mostrato nell'area di notifica."

#: src/sbackup/ui/configgui.py:888
msgid "Backup process started"
msgstr "Processo di backup avviato"

#: src/sbackup/ui/configgui.py:893 src/sbackup/ui/configgui.py:1661
#: src/sbackup/ui/configgui.py:2038
#, python-format
msgid "Unexpected dialog response: %s"
msgstr ""

#: src/sbackup/ui/configgui.py:967
msgid "Include file..."
msgstr ""

#: src/sbackup/ui/configgui.py:974 src/sbackup/ui/configgui.py:1029
msgid "All files"
msgstr "Tutti i file"

#: src/sbackup/ui/configgui.py:994
msgid "Include folder..."
msgstr ""

#: src/sbackup/ui/configgui.py:1022
msgid "Exclude file..."
msgstr ""

#: src/sbackup/ui/configgui.py:1045
msgid "Exclude folder..."
msgstr ""

#: src/sbackup/ui/configgui.py:1310
msgid "Configuration has changed"
msgstr ""

#: src/sbackup/ui/configgui.py:1311
msgid ""
"There are unsaved modifications. Please save the configuration or revert "
"these changes before testing the mail settings."
msgstr ""

#: src/sbackup/ui/configgui.py:1317 src/sbackup/ui/configgui.py:1323
msgid "Test mail settings"
msgstr "Provare le impostazioni delle email"

#: src/sbackup/ui/configgui.py:1318
msgid "The test failed with following output:"
msgstr ""

#: src/sbackup/ui/configgui.py:1324
msgid "The test was successful."
msgstr ""

#: src/sbackup/ui/configgui.py:1407 src/sbackup/ui/configgui.py:1450
#, python-format
msgid ""
"The given expression contains unsupported characters ('%s'). Currently it is "
"not possible to use these characters in exclude expressions."
msgstr ""

#: src/sbackup/ui/configgui.py:1410 src/sbackup/ui/configgui.py:1453
msgid "Unsupported character"
msgstr ""

#: src/sbackup/ui/configgui.py:1621
msgid "Connect to remote destination"
msgstr ""

#: src/sbackup/ui/configgui.py:1669
msgid "Mount was sucessful (no errors)"
msgstr ""

#: src/sbackup/ui/configgui.py:1680
msgid "Unable to mount host"
msgstr ""

#: src/sbackup/ui/configgui.py:1689
msgid "Umount was sucessful (no errors)"
msgstr ""

#: src/sbackup/ui/configgui.py:1699
msgid "Unable to unmount host"
msgstr ""

#: src/sbackup/ui/configgui.py:1729
msgid "Perfom tests on remote host"
msgstr ""

#: src/sbackup/ui/configgui.py:1742
msgid "Unable to access remote destination"
msgstr ""

#: src/sbackup/ui/configgui.py:1746
msgid "All tests passed"
msgstr ""

#: src/sbackup/ui/configgui.py:1910
msgid ""
"The given name of the new profile is empty. Please enter a valid profile "
"name."
msgstr ""

#: src/sbackup/ui/configgui.py:1911 src/sbackup/ui/configgui.py:1918
msgid "Profile name not valid"
msgstr ""

#: src/sbackup/ui/configgui.py:1917
msgid ""
"The given name of the new profile already exists. Please enter another name."
msgstr ""

#: src/sbackup/ui/configgui.py:1919
msgid "Renaming of profiles is not supported."
msgstr ""

#: src/sbackup/ui/configgui.py:1949
#, python-format
msgid ""
"<b>Delete configuration profile?</b>\n"
"\n"
"You are trying to remove a configuration profile. You will not be able to "
"restore it. If you are not sure, use the 'enable|disable' functionality "
"instead.\n"
"\n"
"Do you really want to delete the profile '%(name)s'?"
msgstr ""

#: src/sbackup/ui/configgui.py:2022
#, python-format
msgid ""
"<big><b>Set default values for current profile?</b></big>\n"
"This will restore the default values for the profile currently edited: "
"'%s'.\n"
"\n"
"These predefined settings are recommended for most users. Check whether they "
"are appropriate for your use before saving the changed configuration."
msgstr ""

#: src/sbackup/ui/configgui.py:2032
msgid "Default settings are being applied."
msgstr ""

#: src/sbackup/ui/configgui.py:2057
msgid ""
"<b>Unable to remove default profile</b>\n"
"\n"
"The default profile cannot be removed. In the case you want to use just a "
"single profile, please set up the default profile accordingly."
msgstr ""

#: src/sbackup/ui/configgui.py:2071
msgid ""
"<b>Unable to remove default profile</b>\n"
"\n"
"The default profile cannot be disabled. In the case you want to use just a "
"single profile, please set up the default profile accordingly."
msgstr ""

#: src/sbackup/ui/configgui.py:2085
msgid ""
"<b>No backup profile found.</b>\n"
"\n"
"No default profile was found. You are probably running Simple Backup for the "
"first time. A backup profile using default values was created.\n"
"\n"
"Please modify the settings according to your needs and save the "
"configuration in order to use it."
msgstr ""

#: src/sbackup/ui/configgui.py:2098
msgid "Please select a profile."
msgstr ""

#: src/sbackup/ui/indicator_core.py:117
msgid "there was a problem initializing the pynotify module"
msgstr ""

#: src/sbackup/ui/indicator_core.py:148 src/sbackup/ui/indicator_core.py:197
#: src/sbackup/ui/indicator_core.py:225 src/sbackup/ui/indicator_core.py:247
#, python-format
msgid "Connection to notification-daemon failed: %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:310
msgid "Simple Backup"
msgstr ""

#: src/sbackup/ui/indicator_core.py:316
msgid "Show message windows"
msgstr ""

#: src/sbackup/ui/indicator_core.py:358 src/sbackup/ui/indicator_core.py:816
msgid "Cancel Backup"
msgstr ""

#: src/sbackup/ui/indicator_core.py:420
msgid "Connection to D-Bus service lost."
msgstr ""

#: src/sbackup/ui/indicator_core.py:445
msgid "re-connection was successful"
msgstr ""

#: src/sbackup/ui/indicator_core.py:484
msgid ""
"No backup in progress and connection to D-Bus service lost. Simple Backup "
"Indicator is being terminated."
msgstr ""

#: src/sbackup/ui/indicator_core.py:513
msgid "Starting backup session"
msgstr ""

#: src/sbackup/ui/indicator_core.py:527
msgid "Ending Backup Session"
msgstr ""

#: src/sbackup/ui/indicator_core.py:540
#, python-format
msgid "Unknown D-Bus event `%s` received."
msgstr ""

#: src/sbackup/ui/indicator_core.py:581
msgid "Try again"
msgstr ""

#: src/sbackup/ui/indicator_core.py:651
msgid ""
"Attempt of starting another instance of Simple Backup while this one is "
"already running."
msgstr ""

#: src/sbackup/ui/indicator_core.py:661
#, python-format
msgid "Unable to present window: %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:677
#, python-format
msgid "Do you really want to cancel the backup process of profile '%s'?"
msgstr ""

#: src/sbackup/ui/indicator_core.py:681
msgid "Cancel running backup process?"
msgstr ""

#: src/sbackup/ui/indicator_core.py:698
msgid "Unable to cancel backup process."
msgstr ""

#: src/sbackup/ui/indicator_core.py:760
#, python-format
msgid "Profile: %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:761
#, python-format
msgid "Size of backup: %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:762
#, python-format
msgid "%.1f%% processed"
msgstr ""

#: src/sbackup/ui/indicator_core.py:763
#, python-format
msgid "Remaining time: %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:809
#, python-format
msgid "PID of backup process being canceled: %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:814
#, python-format
msgid "Unable to send signal to process %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:815
#, python-format
msgid "Sending signal using gksu to process %s"
msgstr ""

#: src/sbackup/ui/indicator_core.py:819
#, python-format
msgid "Sending signal using gksu to process %s failed"
msgstr ""

#: src/sbackup/ui/indicator_core.py:854
#, python-format
msgid ""
"<b>Unable to find specified target directory</b>\n"
"\n"
"The specified target directory '%s' was not found.\n"
"\n"
msgstr ""

#: src/sbackup/ui/indicator_core.py:855
#, python-format
msgid ""
"You can try to use the specified target again or cancel the profile "
"execution. The specified destination is automatically used in %s seconds."
msgstr ""

#: src/sbackup/ui/indicator_core.py:882 src/sbackup/ui/indicator_core.py:924
#: src/sbackup/ui/indicator_core.py:942 src/sbackup/ui/indicator_core.py:950
#: src/sbackup/ui/indicator_core.py:967
msgid "unknown"
msgstr ""

#: src/sbackup/ui/indicator_core.py:903
msgid "less than 1 minute"
msgstr ""

#: src/sbackup/ui/indicator_core.py:905
msgid "about 2 minutes"
msgstr ""

#: src/sbackup/ui/indicator_core.py:907
msgid "about 3 minutes"
msgstr ""

#: src/sbackup/ui/indicator_core.py:909
msgid "about 4 minutes"
msgstr ""

#: src/sbackup/ui/indicator_core.py:911
msgid "about 5 minutes"
msgstr ""

#: src/sbackup/ui/indicator_core.py:913
#, python-format
msgid "about %.0f minutes"
msgstr ""

#: src/sbackup/ui/indicator_core.py:923
msgid "In progress"
msgstr ""

#: src/sbackup/ui/indicator_core.py:933 src/sbackup/ui/indicator_core.py:959
msgid "finished"
msgstr ""

#: src/sbackup/ui/indicator_core.py:941
msgid "Progress: unknown"
msgstr ""

#: src/sbackup/ui/indicator_core.py:948
msgid "Backup is being prepared"
msgstr ""

#: src/sbackup/ui/indicator_core.py:949
msgid "Collecting file info"
msgstr ""

#: src/sbackup/ui/indicator_core.py:958
msgid "Progress: canceled"
msgstr ""

#: src/sbackup/ui/indicator_core.py:980
msgid "An error occurred"
msgstr ""

#: src/sbackup/ui/indicator_core.py:1013
msgid "Another `Simple Backup Indicator` is already running."
msgstr ""

#: src/sbackup/ui/indicator_core.py:1037
#, python-format
msgid "Initialization of GTK+ failed: %s"
msgstr ""

#: src/sbackup/ui/misc.py:294
#, python-format
msgid "%s   (Administrator mode)"
msgstr ""

#: src/sbackup/ui/misc.py:324
#, python-format
msgid ""
"An uncaught error occurred. Close this message window and restart the "
"application.\n"
"\n"
"Please report this error on https://bugs.launchpad.net/sbackup.\n"
"\n"
"%s"
msgstr ""

#: src/sbackup/ui/misc.py:325
msgid "Sorry, this should not have happened"
msgstr ""

#: src/sbackup/ui/restoregui.py:78
msgid "Restore..."
msgstr "Ripristina..."

#: src/sbackup/ui/restoregui.py:79 data/ui/sbackup-restore.glade:765
msgid "Restore as..."
msgstr "Ripristina come..."

#: src/sbackup/ui/restoregui.py:80
msgid "Revert..."
msgstr "Reimposta..."

#: src/sbackup/ui/restoregui.py:81 data/ui/sbackup-restore.glade:797
msgid "Revert as..."
msgstr "Reimposta come..."

#: src/sbackup/ui/restoregui.py:128 data/ui/sbackup-restore.glade:111
#: data/ui/sbackup-restore.glade:511
msgid "n.a."
msgstr ""

#: src/sbackup/ui/restoregui.py:146 src/sbackup/ui/restoregui.py:163
msgid "Snapshots"
msgstr "Immagini"

#: src/sbackup/ui/restoregui.py:147
msgid "Version"
msgstr "Versione"

#: src/sbackup/ui/restoregui.py:154 data/ui/sbackup-config.glade:4063
msgid "Path"
msgstr "Percorso"

#: src/sbackup/ui/restoregui.py:159
msgid "State"
msgstr "Stato"

#: src/sbackup/ui/restoregui.py:187
msgid "Connect to destination..."
msgstr ""

#: src/sbackup/ui/restoregui.py:211
msgid "Specified path does not exist"
msgstr ""

#: src/sbackup/ui/restoregui.py:257
msgid "Ready"
msgstr "Pronto"

#: src/sbackup/ui/restoregui.py:371
msgid "No destination specified"
msgstr ""

#: src/sbackup/ui/restoregui.py:388
msgid "Choose a source folder"
msgstr "Scegliere una cartella"

#: src/sbackup/ui/restoregui.py:405
msgid "Reading snapshots..."
msgstr ""

#: src/sbackup/ui/restoregui.py:428
msgid "Reading directory content..."
msgstr ""

#: src/sbackup/ui/restoregui.py:458 src/sbackup/ui/restoregui.py:496
msgid "Loading ..."
msgstr "Caricamento..."

#: src/sbackup/ui/restoregui.py:539
msgid "Reading files from snapshot..."
msgstr ""

#: src/sbackup/ui/restoregui.py:552
msgid "Simple Backup restore error"
msgstr ""

#: src/sbackup/ui/restoregui.py:553
msgid "An error occurred while reading snapshot"
msgstr ""

#: src/sbackup/ui/restoregui.py:557
msgid "This snapshot seems empty."
msgstr "Questa immagine sembra vuota."

#: src/sbackup/ui/restoregui.py:576
msgid "Reading backup snapshot..."
msgstr "Lettura dell'immagine di backup..."

#: src/sbackup/ui/restoregui.py:599
msgid "No backups found for this day."
msgstr ""

#: src/sbackup/ui/restoregui.py:614 src/sbackup/ui/restoregui.py:771
#, python-format
msgid ""
"Snapshot version is not supported (Only %(supportedversion)s is supported). "
"Version '%(currentversion)s' found."
msgstr ""

#: src/sbackup/ui/restoregui.py:643
msgid "Select restore location"
msgstr "Seleziona posizione di ripristino"

#: src/sbackup/ui/restoregui.py:662
#, python-format
msgid "Do you really want to revert '%s'?"
msgstr ""

#: src/sbackup/ui/restoregui.py:676
msgid "Select revert location"
msgstr "Selezionare la posizione di reimpostazione"

#: src/sbackup/ui/restoregui.py:685
#, python-format
msgid "Do you really want to revert '%(source)s' to '%(dir)s'?"
msgstr ""

#: src/sbackup/ui/restoregui.py:763
msgid "Reading snapshot..."
msgstr ""

#: src/sbackup/ui/restoregui.py:782
#, python-format
msgid ""
"Deleting the selected snapshot `%s` will remove your backup for this "
"particular point in time. You cannot undo this operation.\n"
"\n"
"Are you sure that you want to remove the snapshot permanently?"
msgstr ""

#: src/sbackup/ui/restoregui.py:786
msgid "Do you really want to remove snapshot?"
msgstr ""

#: src/sbackup/ui/restoregui.py:795
#, python-format
msgid ""
"While attempting to delete snapshot the following error occurred:\n"
"%s"
msgstr ""

#: src/sbackup/ui/restoregui.py:798
msgid "Unable to delete snapshot"
msgstr ""

#: src/sbackup/ui/restoregui.py:804
#, python-format
msgid ""
"The selected snapshot '%s' is referenced by more recent snapshots as base "
"snapshot.\n"
"\n"
"Remove all of these child snapshots in order to delete this snapshot."
msgstr ""

#: src/sbackup/ui/restoregui.py:806
msgid "Unable to remove snapshot"
msgstr ""

#: src/sbackup/ui/restoregui.py:814
msgid "Termination in progress"
msgstr ""

#: src/sbackup/ui/restoregui.py:830 src/sbackup/ui/restoregui.py:836
#: src/sbackup/ui/restoregui.py:842 src/sbackup/ui/restoregui.py:848
#: data/ui/sbackup-restore.glade:959
msgid "Simple Backup restoration"
msgstr ""

#: src/sbackup/ui/restoregui.py:831 src/sbackup/ui/restoregui.py:837
msgid "<b>Restoring of selected files</b>"
msgstr "<b>Ripristino del file selezionato</b>"

#: src/sbackup/ui/restoregui.py:832
#, python-format
msgid "Restoring of <tt>'%s'</tt> is in progress."
msgstr "Ripristino di <tt>«%s»</tt> in corso."

#: src/sbackup/ui/restoregui.py:833
#, python-format
msgid "Restoring of <tt>'%s'</tt> was successful."
msgstr ""

#: src/sbackup/ui/restoregui.py:834
#, python-format
msgid ""
"Restoring of <tt>'%s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""

#: src/sbackup/ui/restoregui.py:838
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> is in progress."
msgstr ""
"Ripristino di <tt>«%(source)s»</tt>\n"
"in <tt>«%(dirname)s»</tt> in corso."

#: src/sbackup/ui/restoregui.py:839
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was successful."
msgstr ""

#: src/sbackup/ui/restoregui.py:840
#, python-format
msgid ""
"Restoring of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""

#: src/sbackup/ui/restoregui.py:843 src/sbackup/ui/restoregui.py:849
msgid "<b>Reverting selected files</b>"
msgstr "<b>Reimpostazione dei file selezionati</b>"

#: src/sbackup/ui/restoregui.py:844
#, python-format
msgid "Reverting of <tt>'%s'</tt> is in progress.\n"
msgstr "Reimpostazione di <tt>«%s»</tt> in corso.\n"

#: src/sbackup/ui/restoregui.py:845
#, python-format
msgid "Reverting of <tt>'%s'</tt> was successful."
msgstr ""

#: src/sbackup/ui/restoregui.py:846
#, python-format
msgid ""
"Reverting of <tt>'%s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""

#: src/sbackup/ui/restoregui.py:850
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> is in progress."
msgstr ""
"Reimpostazione di <tt>«%(source)s»</tt>\n"
"in <tt>«%(dirname)s»</tt> in corso."

#: src/sbackup/ui/restoregui.py:851
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was successful."
msgstr ""

#: src/sbackup/ui/restoregui.py:852
#, python-format
msgid ""
"Reverting of <tt>'%(source)s'</tt>\n"
"to <tt>'%(dirname)s'</tt> was not successful.\n"
"\n"
"Following error occurred:\n"
msgstr ""

#: src/sbackup/util/__init__.py:439
#, python-format
msgid "%(mb)d MiB %(kb)d KiB"
msgstr ""

#: src/sbackup/util/__init__.py:442
#, python-format
msgid "%(mb)d MiB %(kb)d KiB %(bytes)d"
msgstr ""

#: src/sbackup/util/__init__.py:447
#, python-format
msgid "%(mb)d MB %(kb)d kB"
msgstr ""

#: src/sbackup/util/__init__.py:450
#, python-format
msgid "%(mb)d MB %(kb)d kB %(bytes)d"
msgstr ""

#: src/sbackup/util/filecollect.py:335
#, python-format
msgid "File '%(file)s' is not accessable with error '%(error)s'."
msgstr ""

#: src/sbackup/util/filecollect.py:351
#, python-format
msgid ""
"File '%(file)s' cannot be opened for read access. Operation timed out."
msgstr ""

#: src/sbackup/util/filecollect.py:355
#, python-format
msgid ""
"File '%(file)s' cannot be opened for read access with error '%(error)s'."
msgstr ""

#: src/sbackup/util/filecollect.py:372
#, python-format
msgid "Symbolic link '%(path)s' -> '%(ln_target)s' is a circular symlink."
msgstr ""

#: src/sbackup/util/filecollect.py:388
#, python-format
msgid "File '%(file)s' is backup's target directory."
msgstr ""

#: src/sbackup/util/filecollect.py:393
#, python-format
msgid "Path '%(file)s' defined in excludes list."
msgstr ""

#: src/sbackup/util/filecollect.py:401
#, python-format
msgid "File '%(file)s' matches regular expression '%(regex)s'."
msgstr ""

#: src/sbackup/util/filecollect.py:419
#, python-format
msgid ""
"File '%(file)s' exceeds maximum file size ( %(filesize)s > %(maxsize)s)."
msgstr ""

#: src/sbackup/util/filecollect.py:497
#, python-format
msgid "Error while checking directory '%(dir)s': %(error)s."
msgstr ""

#: src/sbackup/util/filecollect.py:548
msgid "Empty regular expression found. Skipped."
msgstr ""

#: src/sbackup/util/filecollect.py:554
#, python-format
msgid "Invalid regular expression ('%s') found. Skipped."
msgstr ""

#: src/sbackup/util/filecollect.py:573
msgid "No directories to backup defined."
msgstr ""

#: src/sbackup/util/lock.py:76
msgid "Another application instance is already running."
msgstr ""

#: src/sbackup/util/lock.py:78
msgid "Invalid lock file found. Is being removed."
msgstr ""

#: src/sbackup/util/lock.py:128 src/sbackup/util/lock.py:142
#, python-format
msgid "Unable to remove lock file: %s"
msgstr ""

#: src/sbackup/util/lock.py:132 src/sbackup/util/lock.py:144
msgid "Unable to remove lock file: File not found."
msgstr ""

#: data/ui/sbackup-config.glade:11
msgid "Exclude file type"
msgstr "Escludi tipo di file"

#: data/ui/sbackup-config.glade:26
msgid "Standard file types:"
msgstr "Tipi di file standard:"

#: data/ui/sbackup-config.glade:63
msgid "Custom defined file type with "
msgstr "Tipo di file definito dall'utente con "

#: data/ui/sbackup-config.glade:93
msgid "file extension"
msgstr "estensione del file"

#: data/ui/sbackup-config.glade:163
msgid "Exclude by regex"
msgstr "Escludi con espressione regolare"

#: data/ui/sbackup-config.glade:180
msgid ""
"Enter a regular expression.\n"
"Files and directories matching this expression will be excluded from backup."
msgstr ""
"Inserire un'espressione regolare.\n"
"I file e le directory corrispondenti a a questa espressione verranno esclusi "
"dal backup."

#: data/ui/sbackup-config.glade:257
msgid "Enter the remote target to include"
msgstr "Inserire la destinazione remota da includere"

#: data/ui/sbackup-config.glade:278
msgid "Choose a plugin to get the format"
msgstr "Scegliere un plugin per ottenere il formato"

#: data/ui/sbackup-config.glade:295
msgid "Choose your plugin :"
msgstr "Scegliere il plugin:"

#: data/ui/sbackup-config.glade:367
msgid "Check"
msgstr "Controllo"

#: data/ui/sbackup-config.glade:479
msgid ""
"<b>Save changed configuration?</b>\n"
"\n"
"The configuration has changed. If you want to use the modified "
"configuration, you have to save it.\n"
"\n"
"Do you want to save the configuration now?"
msgstr ""

#: data/ui/sbackup-config.glade:572
msgid "Configuration Profile Manager"
msgstr ""

#: data/ui/sbackup-config.glade:594
msgid ""
"You can set up multiple configuration profiles which are processed when "
"performing a backup. Each profile has its own set of settings including "
"backup destination, backup format etc."
msgstr ""

#: data/ui/sbackup-config.glade:613
msgid "<b>Configuration profiles</b>"
msgstr "<b>Profili di configurazione</b>"

#: data/ui/sbackup-config.glade:785
msgid ""
"<b>Add new profile</b>\n"
"\n"
"Please enter the new profile name and set the according checkbox in order to "
"enable resp. disable it."
msgstr ""

#: data/ui/sbackup-config.glade:810
msgid "Profile name"
msgstr ""

#: data/ui/sbackup-config.glade:836
msgid "Enabled"
msgstr ""

#: data/ui/sbackup-config.glade:915 data/ui/sbackup-restore.glade:7
msgid "Simple Backup Suite"
msgstr "Strumento di backup"

#: data/ui/sbackup-config.glade:932
msgid "_File"
msgstr "_File"

#: data/ui/sbackup-config.glade:971
msgid "Save as..."
msgstr ""

#: data/ui/sbackup-config.glade:1008
msgid "_Tools"
msgstr "S_trumenti"

#: data/ui/sbackup-config.glade:1016 data/ui/sbackup-config.glade:1140
msgid "Set default settings..."
msgstr ""

#: data/ui/sbackup-config.glade:1037
msgid "Profile Manager..."
msgstr ""

#: data/ui/sbackup-config.glade:1058
msgid "Make backup now"
msgstr ""

#: data/ui/sbackup-config.glade:1079
msgid "_Help"
msgstr "A_iuto"

#: data/ui/sbackup-config.glade:1087
msgid "_View all help topics"
msgstr ""

#: data/ui/sbackup-config.glade:1103
msgid "_About this program"
msgstr ""

#: data/ui/sbackup-config.glade:1154
msgid "Reload configuration"
msgstr ""

#: data/ui/sbackup-config.glade:1168
msgid "Save configuration"
msgstr ""

#: data/ui/sbackup-config.glade:1191
msgid "Make a backup now"
msgstr ""

#: data/ui/sbackup-config.glade:1214
msgid "Open the profile manager"
msgstr ""

#: data/ui/sbackup-config.glade:1215
msgid "Profiles"
msgstr "Profili"

#: data/ui/sbackup-config.glade:1253
msgid ""
"none\n"
"gzip\n"
"bzip2"
msgstr ""
"Nessuno\n"
"gzip\n"
"bzip2"

#: data/ui/sbackup-config.glade:1271
msgid ""
"Compression format\n"
"Default is set to uncompressed backups."
msgstr ""

#: data/ui/sbackup-config.glade:1290 data/ui/sbackup-config.glade:1403
msgid ""
"You can split the snapshot to make backup on some filesystem that doesn't "
"support large files. This functionality can not be used if the backup is "
"compressed."
msgstr ""

#: data/ui/sbackup-config.glade:1330
msgid "Do a full backup at least once every"
msgstr "Eseguire un backup integrale almeno ogni:"

#: data/ui/sbackup-config.glade:1339
msgid ""
"Unless a set number of days has passed since the last full backup, "
"incremental backups will be done."
msgstr ""

#: data/ui/sbackup-config.glade:1356 data/ui/sbackup-config.glade:3015
msgid "days"
msgstr "giorni"

#: data/ui/sbackup-config.glade:1370
msgid " "
msgstr " "

#: data/ui/sbackup-config.glade:1380 data/ui/sbackup-config.glade:2323
msgid "MiB"
msgstr "MiB"

#: data/ui/sbackup-config.glade:1405
msgid "Split backup archives into several chunks"
msgstr ""

#: data/ui/sbackup-config.glade:1438 data/ui/sbackup-config.glade:2627
#: data/ui/sbackup-config.glade:2863 data/ui/sbackup-config.glade:3111
#: data/ui/sbackup-config.glade:3856
msgid "Help"
msgstr ""

#: data/ui/sbackup-config.glade:1442 data/ui/sbackup-config.glade:2632
msgid "Show help topic about configuration GUI."
msgstr ""

#: data/ui/sbackup-config.glade:1475
msgid "General"
msgstr "Generale"

#: data/ui/sbackup-config.glade:1495
msgid "<b>Included files and directories</b>"
msgstr ""

#: data/ui/sbackup-config.glade:1570 data/ui/sbackup-config.glade:1818
#: data/ui/sbackup-config.glade:2023 data/ui/sbackup-config.glade:2181
msgid "Remove"
msgstr ""

#: data/ui/sbackup-config.glade:1620 data/ui/sbackup-config.glade:1868
msgid "Add File"
msgstr "Aggiungi file"

#: data/ui/sbackup-config.glade:1671 data/ui/sbackup-config.glade:1919
msgid "Add Directory"
msgstr "Aggiungi cartella"

#: data/ui/sbackup-config.glade:1718
msgid "Include"
msgstr "Includi"

#: data/ui/sbackup-config.glade:1739
msgid "<b>Excluded files and directories</b>"
msgstr ""

#: data/ui/sbackup-config.glade:1952
msgid "Paths"
msgstr "Percorsi"

#: data/ui/sbackup-config.glade:2074 data/ui/sbackup-config.glade:2232
msgid "Add"
msgstr ""

#: data/ui/sbackup-config.glade:2109
msgid "File types"
msgstr "Formati dei file"

#: data/ui/sbackup-config.glade:2267
msgid ""
"Regular\n"
"Expressions"
msgstr ""

#: data/ui/sbackup-config.glade:2288
msgid "Do not backup files bigger than"
msgstr ""

#: data/ui/sbackup-config.glade:2344
msgid "Follow symbolic links"
msgstr ""

#: data/ui/sbackup-config.glade:2373
msgid "Others"
msgstr "Altri"

#: data/ui/sbackup-config.glade:2400
msgid "Exclude"
msgstr "Escludi"

#: data/ui/sbackup-config.glade:2421
msgid "Use default backup directory"
msgstr ""

#: data/ui/sbackup-config.glade:2446
msgid "/var/backup"
msgstr ""

#: data/ui/sbackup-config.glade:2472
msgid "Use custom local backup directory"
msgstr "Usare la directory di backup personalizzata"

#: data/ui/sbackup-config.glade:2500
msgid "Select the destination folder"
msgstr "Seleziona cartella di destinazione"

#: data/ui/sbackup-config.glade:2526
msgid "Use a remote site"
msgstr ""

#: data/ui/sbackup-config.glade:2568
msgid "ssh://username:password@example.com/remote/dir/"
msgstr "ssh://nomeutente:password@esempio.it/directory/remota/"

#: data/ui/sbackup-config.glade:2580
msgid "Connect..."
msgstr ""

#: data/ui/sbackup-config.glade:2672
msgid ""
"<i>The selected destination is not writeable with current permissions. "
"Backups cannot be stored there.</i>"
msgstr ""

#: data/ui/sbackup-config.glade:2704
msgid "Destination"
msgstr "Destinazione"

#: data/ui/sbackup-config.glade:2725
msgid "_No scheduled backups"
msgstr ""

#: data/ui/sbackup-config.glade:2742
msgid "_Simple"
msgstr ""

#: data/ui/sbackup-config.glade:2747
msgid ""
"This option will make a backup not at a precise time but when the computer "
"is up. "
msgstr ""

#: data/ui/sbackup-config.glade:2761
msgid "_Custom"
msgstr ""

#: data/ui/sbackup-config.glade:2781
msgid "Do backups"
msgstr ""

#: data/ui/sbackup-config.glade:2798
msgid "Cron time definition"
msgstr ""

#: data/ui/sbackup-config.glade:2834
msgid ""
"hourly\n"
"daily\n"
"weekly\n"
"monthly"
msgstr ""

#: data/ui/sbackup-config.glade:2867
msgid "Show help topic about scheduled backups."
msgstr ""

#: data/ui/sbackup-config.glade:2905
msgid ""
"<small>You can configure scheduled (i.e. automated) backups either simply by "
"choosing an interval or precisely by a custom cron definition. See \"man 5 "
"crontab\" for cron time definition format.</small>"
msgstr ""

#: data/ui/sbackup-config.glade:2937
msgid "Schedule"
msgstr ""

#: data/ui/sbackup-config.glade:2955
msgid "Enable purging of old backups"
msgstr ""

#: data/ui/sbackup-config.glade:2983
msgid "Simple cut-off: Erase all backups older than"
msgstr ""

#: data/ui/sbackup-config.glade:3039
msgid "Logarithmic"
msgstr "Logaritmica"

#: data/ui/sbackup-config.glade:3065
msgid ""
"<small>Keep progressively less backups into the past:\n"
"Keep all backups from yesterday\n"
"Keep one backup per day from last week\n"
"Keep one backup per week from last month\n"
"Keep one backup per month from last year\n"
"Keep one backup per quarter from 2nd last year\n"
"Keep one backup per year further into past</small>"
msgstr ""

#: data/ui/sbackup-config.glade:3116
msgid "Show help topic about purging of backups."
msgstr ""

#: data/ui/sbackup-config.glade:3152
msgid ""
"<small>Note: Additionally all incomplete and irrecoverable backups will be "
"erased as long as there is a complete backup snapshot made later on.</small>"
msgstr ""
"<small>Nota: gli ulteriori backup incompleti e irrecuperabili verranno "
"cancellati finché vi sarà sempre un backup completo.</small>"

#: data/ui/sbackup-config.glade:3184
msgid "Purging"
msgstr "Pulizia"

#: data/ui/sbackup-config.glade:3186
msgid "Cleaning old backups"
msgstr "Eliminazione vecchi backup"

#: data/ui/sbackup-config.glade:3209
msgid "<b>Logging</b>"
msgstr ""

#: data/ui/sbackup-config.glade:3234
msgid "Debug is just for debbuging purpose.Info is the recommended setting"
msgstr "Debug è solo per il debug. L'impostazione raccomandata è Info"

#: data/ui/sbackup-config.glade:3236
msgid "Log level"
msgstr ""

#: data/ui/sbackup-config.glade:3248
msgid "Debug is just for debbuging purpose. Info is the recommended setting."
msgstr ""

#: data/ui/sbackup-config.glade:3274
msgid "Log file directory"
msgstr "Directory del file del registro"

#: data/ui/sbackup-config.glade:3320
msgid "<b>Report by mail</b>"
msgstr ""

#: data/ui/sbackup-config.glade:3350
msgid "From"
msgstr ""

#: data/ui/sbackup-config.glade:3361
msgid "SMTP server"
msgstr ""

#: data/ui/sbackup-config.glade:3375 data/ui/sbackup-config.glade:4053
msgid "Port"
msgstr ""

#: data/ui/sbackup-config.glade:3391
msgid "To"
msgstr ""

#: data/ui/sbackup-config.glade:3478
msgid "Use a username and password"
msgstr "Utilizzare nome utente e password"

#: data/ui/sbackup-config.glade:3508 data/ui/sbackup-config.glade:4075
msgid "Username"
msgstr "Nome utente"

#: data/ui/sbackup-config.glade:3540 data/ui/sbackup-config.glade:4124
msgid "Password"
msgstr "Password"

#: data/ui/sbackup-config.glade:3584
msgid "Use secure connection"
msgstr ""

#: data/ui/sbackup-config.glade:3615
msgid "Choose a certificate file"
msgstr ""

#: data/ui/sbackup-config.glade:3629
msgid "Key"
msgstr "Chiave"

#: data/ui/sbackup-config.glade:3645
msgid "Certificate"
msgstr "Certificato"

#: data/ui/sbackup-config.glade:3659
msgid "Choose a key file"
msgstr ""

#: data/ui/sbackup-config.glade:3731
msgid "Test _mail settings"
msgstr ""

#: data/ui/sbackup-config.glade:3772
msgid "Report"
msgstr "Rapporto"

#: data/ui/sbackup-config.glade:3811
msgid "Warning"
msgstr ""

#: data/ui/sbackup-config.glade:3860
msgid "Show help topic about default values."
msgstr ""

#: data/ui/sbackup-config.glade:3893
msgid "_Set"
msgstr ""

#: data/ui/sbackup-config.glade:3935
msgid "Set remote target"
msgstr ""

#: data/ui/sbackup-config.glade:3957
msgid "Type of service"
msgstr ""

#: data/ui/sbackup-config.glade:3997
msgid "Hostname"
msgstr ""

#: data/ui/sbackup-config.glade:4027
msgid "<b>Details</b>"
msgstr ""

#: data/ui/sbackup-config.glade:4157
msgid "Show password"
msgstr ""

#: data/ui/sbackup-config.glade:4217
msgid "_Connect"
msgstr ""

#: data/ui/sbackup-config.glade:4293
msgid "Make a full backup"
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:7
msgid "Restore files/directories"
msgstr "Ripristina file e directory"

#: data/ui/sbackup-legacy-restore.glade:25
msgid "<b>Restore Source Folder</b>"
msgstr "<b>Cartella da cui ripristinare</b>"

#: data/ui/sbackup-legacy-restore.glade:90
msgid "Available backups:"
msgstr "Backup disponibili:"

#: data/ui/sbackup-legacy-restore.glade:109
msgid ""
"Type in this box text like that:\n"
"\n"
"/home/user/folder - To use a local folder\n"
"ssh://user:password@machine:/remote/folder - To use a ssh location\n"
"ftp://user:password@machine:/remote/folder - To use a ftp location"
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:179
msgid "Use custom:"
msgstr "Personalizzata:"

#: data/ui/sbackup-legacy-restore.glade:200
msgid "Use default:"
msgstr "Predefinita:"

#: data/ui/sbackup-legacy-restore.glade:241
msgid "<b>Files and Folders to restore</b>"
msgstr "<b>File e cartelle da ripristinare</b>"

#: data/ui/sbackup-legacy-restore.glade:345 data/ui/sbackup-restore.glade:782
msgid "Restore"
msgstr "Ripristina"

#: data/ui/sbackup-legacy-restore.glade:390
msgid "Restore As..."
msgstr "Ripristina come..."

#: data/ui/sbackup-legacy-restore.glade:448
msgid "Restoring, this might take some time ..."
msgstr ""

#: data/ui/sbackup-legacy-restore.glade:463
msgid "gtk-cancel"
msgstr ""

#: data/ui/sbackup-restore.glade:38
msgid "<b>Backup destination</b>"
msgstr ""

#: data/ui/sbackup-restore.glade:52
msgid "Displays the manual in Help browser."
msgstr ""

#: data/ui/sbackup-restore.glade:85
msgid "Default profile's destination"
msgstr ""

#: data/ui/sbackup-restore.glade:90
msgid ""
"Set backup destination to the place specified in default configuration "
"profile"
msgstr ""

#: data/ui/sbackup-restore.glade:137
msgid "Custom destination"
msgstr ""

#: data/ui/sbackup-restore.glade:143
msgid ""
"Select a backup destination on your harddisk or at a remote site. Press "
"Apply when ready."
msgstr ""

#: data/ui/sbackup-restore.glade:184
msgid "Choose a destination folder. For remote sites fill URI in text field"
msgstr ""

#: data/ui/sbackup-restore.glade:201
msgid "Change destination to path specified in left text field"
msgstr ""

#: data/ui/sbackup-restore.glade:266
msgid "Select a bold printed date to get the list of backups for that date."
msgstr ""

#: data/ui/sbackup-restore.glade:310
msgid "Available backups"
msgstr ""

#: data/ui/sbackup-restore.glade:398
msgid "Delete snapshot"
msgstr ""

#: data/ui/sbackup-restore.glade:436
msgid "Delete"
msgstr "Elimina"

#: data/ui/sbackup-restore.glade:473
msgid "<b>Snapshot History</b>"
msgstr "<b>Storia dell'immagine</b>"

#: data/ui/sbackup-restore.glade:499
msgid "Current base:"
msgstr ""

#: data/ui/sbackup-restore.glade:540
msgid "Select a snapshot on this list to rebase on it."
msgstr "Selezionare un'immagine nell'elenco per creare la nuova base."

#: data/ui/sbackup-restore.glade:615
msgid "Rebase"
msgstr "Creare la nuova base"

#: data/ui/sbackup-restore.glade:666
msgid "<b>Snapshot Management</b>"
msgstr "<b>Gestione immagine</b>"

#: data/ui/sbackup-restore.glade:705
msgid "Snapshot details"
msgstr ""

#: data/ui/sbackup-restore.glade:770 data/ui/sbackup-restore.glade:787
msgid "Restores files/directories from the selected snapshot"
msgstr ""

#: data/ui/sbackup-restore.glade:802 data/ui/sbackup-restore.glade:821
msgid ""
"Restores files/directories recursively starting from the base snapshot to "
"the selected snapshot"
msgstr ""

#: data/ui/sbackup-restore.glade:816
msgid "Revert"
msgstr "Reimposta"

#: data/ui/sbackup-restore.glade:859
msgid "<b>Restoration Management</b>"
msgstr "<b>Gestione ripristino</b>"

#: data/ui/sbackup-restore.glade:884
msgid "<b>Export Management</b>"
msgstr "<b>Gestione esportazione</b>"

#: data/ui/sbackup-restore.glade:976
msgid "Headline"
msgstr "Intestazione"

#: data/ui/sbackup-restore.glade:989
msgid "Content"
msgstr "Contenuto"

#, python-format
#~ msgid "No need to rebase a full snapshot '%s'"
#~ msgstr "Non è necessario creare la nuova base di un'immagine completa «%s»"

#, python-format
#~ msgid ""
#~ "'%(snapshotToRebase)s'  doesn't have 'base' file , it might have been broken "
#~ msgstr ""
#~ "«%(snapshotToRebase)s» non ha un file «base», potrebbe essere danneggiato "

#, python-format
#~ msgid ""
#~ "Cannot rebase a snapshot on an earlier one : '%(snapshotToRebase)s' <= "
#~ "'%(NewBaseSnapshot)s' "
#~ msgstr ""
#~ "Impossibile creare la nuova base su un'immagine precedente: "
#~ "«%(snapshotToRebase)s» <= «%(NewBaseSnapshot)s» "

#, python-format
#~ msgid "Rebasing '%(current)s' on '%(base)s'"
#~ msgstr "Creare la nuova base «%(current)s» su «%(base)s»"

#, python-format
#~ msgid "Cancelling pull of snapshot '%s'"
#~ msgstr "Annullamento del prelevamento dell'immagine «%s»"

#, python-format
#~ msgid "Upgrading from v1.0 to v1.2: %s"
#~ msgstr "Aggiornamento dalla versione 1.0 alla 1.2: %s"

#, python-format
#~ msgid "Upgrading to v1.3: %s"
#~ msgstr "Aggiornamento alla versione 1.3: %s"

#, python-format
#~ msgid "Upgrading to v1.4: %s"
#~ msgstr "Aggiornamento alla versione 1.4: %s"

#, python-format
#~ msgid "Upgrading to v1.5: %s"
#~ msgstr "Aggiornamento alla versione 1.5: %s"

#~ msgid "The version of the snapshot is greater than the supported one!"
#~ msgstr "La versione dell'immagine è superiore a quella supportata."

#~ msgid "Unable to upgrade snapshot"
#~ msgstr "Impossibile aggiornare l'immagine"

#, python-format
#~ msgid "Do you really want to rebase '%(current)s' on '%(base)s' ?"
#~ msgstr "Creare la nuova base «%(current)s» su «%(base)s»?"

#~ msgid "Upgrade"
#~ msgstr "Aggiorna"

#, python-format
#~ msgid "An error occurred when pulling snapshot '%s'."
#~ msgstr ""
#~ "Si è verificato un errore durante il prelevamento dell'immagine «%s»."

#, python-format
#~ msgid "Base of snapshot '%s' is not set."
#~ msgstr "Base dell'immagine «%s» non impostata."

#~ msgid ""
#~ "There are snapshots stored in outdated snapshot formats. Please upgrade them "
#~ "using 'Simple Backup-Restoration' if you want to use them."
#~ msgstr ""
#~ "Esistono snapshot in formati precedenti. Usare 'Simple Backup-Restoration' "
#~ "se si vuole usarli, grazie."

#, python-format
#~ msgid "The SNAR file already exist for snapshot '%s'. It is not overwritten."
#~ msgstr "Il file SNAR esiste già per lo snapshot '%s'. Non sarà sovrascritto."
